# EEG 3C + 3D — Clean Exact 3B Pipeline

This version starts fresh from `3B_Exact_40_25_Split`. 3C converts every complete 24-row epoch to one sample, fits **separate PCA per subject**, and saves those PCA outputs to Drive. 3D loads the saved PCA outputs and fits separate KNN, Logistic Regression, and SVM models per subject. It reports accuracy, MAE, Spearman, and saves target/prediction for every epoch.

In [ ]:
!pip -q install pandas numpy scipy scikit-learn joblib
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import sys
import importlib
from pathlib import Path

CODE_DIR = '/content/drive/MyDrive/EEG Shared/Code/Code Luke'
if CODE_DIR not in sys.path:
    sys.path.insert(0, CODE_DIR)

import eeg_3c_exact3b_saved_pca
import eeg_3d_models_from_saved_pca
importlib.reload(eeg_3c_exact3b_saved_pca)
importlib.reload(eeg_3d_models_from_saved_pca)

from eeg_3c_exact3b_saved_pca import build_and_save_pca_from_exact3b
from eeg_3d_models_from_saved_pca import run_models_from_saved_pca, combine_all_six_predictions

print('3C + 3D functions loaded.')

3C + 3D functions loaded.

In [ ]:
SPLIT_FOLDER = Path(
    '/content/drive/MyDrive/EEG Shared/Processed_data/'
    'Kosachenko_All_Subjects/3B_Exact_40_25_Split'
)

PCA_OUTPUT_FOLDER = Path(
    '/content/drive/MyDrive/EEG Shared/Processed_data/'
    'Kosachenko_All_Subjects/3C_PCA_Outputs_Clean'
)

RESULTS_FOLDER = Path(
    '/content/drive/MyDrive/EEG Shared/Results/Luke/'
    '3D_Models_From_Clean_PCA'
)

TARGET_COLUMN = 'load_in_sequence'
EPOCH_ROWS = 24
PC_COUNT = 20
CHUNK_ROWS = 50000

# Keep False while developing/tuning. Change to True only when you are ready
# to process the final 25 holdout subjects too.
INCLUDE_FINAL_25_IN_3C = False

print('3B:', SPLIT_FOLDER)
print('PCA:', PCA_OUTPUT_FOLDER)
print('Results:', RESULTS_FOLDER)

3B: /content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split
PCA: /content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3C_PCA_Outputs_Clean
Results: /content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA

## 3C — Fresh 3B → 24-row epochs → PCA → saved to Drive

This deliberately **does not reuse the old 3C caches**. It rereads the current repaired 3B files, verifies subject membership across train/validation/holdout, then saves one `pca_outputs.npz` per subject.

In [ ]:
pca_manifest = build_and_save_pca_from_exact3b(
    split_folder=SPLIT_FOLDER,
    pca_output_folder=PCA_OUTPUT_FOLDER,
    target_column=TARGET_COLUMN,
    epoch_rows=EPOCH_ROWS,
    pc_count=PC_COUNT,
    chunk_rows=CHUNK_ROWS,
    include_holdout_subjects=INCLUDE_FINAL_25_IN_3C,
)

display(pca_manifest.head())
print('Subjects saved:', len(pca_manifest))

Feature columns per row: 99
Flattened dimensions per epoch: 2376
Target: load_in_sequence

Reading DEVELOPMENT train...

KeyboardInterrupt:

In [ ]:
holdout_pca_manifest = build_and_save_pca_from_exact3b(
    split_folder=SPLIT_FOLDER,
    pca_output_folder=PCA_OUTPUT_FOLDER,
    target_column=TARGET_COLUMN,
    epoch_rows=EPOCH_ROWS,
    pc_count=PC_COUNT,
    chunk_rows=50000,
    include_holdout_subjects=True,
)

Feature columns per row: 99
Flattened dimensions per epoch: 2376
Target: load_in_sequence

Reading DEVELOPMENT train...
  train.csv: chunk 5, usable epochs=9624
  train.csv: chunk 10, usable epochs=19240
  train.csv: chunk 15, usable epochs=28822
Reading DEVELOPMENT validation...
  validation.csv: chunk 5, usable epochs=9587
Reading DEVELOPMENT holdout...
  holdout.csv: chunk 5, usable epochs=9604

Development subjects verified: 40
development 1/40 sub-034 saved | train/val/hold=733/359/366 | PCs=20
development 2/40 sub-035 saved | train/val/hold=733/367/358 | PCs=20
development 3/40 sub-036 saved | train/val/hold=740/358/360 | PCs=20
development 4/40 sub-038 saved | train/val/hold=719/370/369 | PCs=20
development 5/40 sub-042 saved | train/val/hold=736/375/374 | PCs=20
development 6/40 sub-043 saved | train/val/hold=728/362/368 | PCs=20
development 7/40 sub-044 saved | train/val/hold=733/364/361 | PCs=20
development 8/40 sub-045 saved | train/val/hold=743/355/360 | PCs=20
development 9/40 sub-048 saved | train/val/hold=731/367/360 | PCs=20
development 10/40 sub-051 saved | train/val/hold=721/369/368 | PCs=20
development 11/40 sub-052 saved | train/val/hold=731/359/368 | PCs=20
development 12/40 sub-053 saved | train/val/hold=727/369/362 | PCs=20
development 13/40 sub-054 saved | train/val/hold=741/355/362 | PCs=20
development 14/40 sub-055 saved | train/val/hold=722/369/367 | PCs=20
development 15/40 sub-056 saved | train/val/hold=728/367/363 | PCs=20
development 16/40 sub-058 saved | train/val/hold=740/358/360 | PCs=20
development 17/40 sub-059 saved | train/val/hold=721/364/373 | PCs=20
development 18/40 sub-062 saved | train/val/hold=733/364/361 | PCs=20
development 19/40 sub-065 saved | train/val/hold=725/370/363 | PCs=20
development 20/40 sub-067 saved | train/val/hold=736/363/359 | PCs=20
development 21/40 sub-068 saved | train/val/hold=716/372/370 | PCs=20
development 22/40 sub-069 saved | train/val/hold=716/371/371 | PCs=20
development 23/40 sub-070 saved | train/val/hold=732/358/368 | PCs=20
development 24/40 sub-073 saved | train/val/hold=729/360/369 | PCs=20
development 25/40 sub-074 saved | train/val/hold=717/374/367 | PCs=20
development 26/40 sub-076 saved | train/val/hold=743/356/359 | PCs=20
development 27/40 sub-077 saved | train/val/hold=719/365/374 | PCs=20
development 28/40 sub-079 saved | train/val/hold=729/370/359 | PCs=20
development 29/40 sub-080 saved | train/val/hold=733/365/360 | PCs=20
development 30/40 sub-081 saved | train/val/hold=745/354/359 | PCs=20
development 31/40 sub-083 saved | train/val/hold=724/372/362 | PCs=20
development 32/40 sub-085 saved | train/val/hold=736/360/362 | PCs=20
development 33/40 sub-087 saved | train/val/hold=730/361/367 | PCs=20
development 34/40 sub-088 saved | train/val/hold=735/366/357 | PCs=20
development 35/40 sub-090 saved | train/val/hold=745/354/359 | PCs=20
development 36/40 sub-091 saved | train/val/hold=721/367/370 | PCs=20
development 37/40 sub-093 saved | train/val/hold=729/369/360 | PCs=20
development 38/40 sub-095 saved | train/val/hold=720/365/373 | PCs=20
development 39/40 sub-096 saved | train/val/hold=721/366/371 | PCs=20
development 40/40 sub-097 saved | train/val/hold=734/365/359 | PCs=20

Reading HOLDOUT-SUBJECT train...
  train.csv: chunk 5, usable epochs=9619
  train.csv: chunk 10, usable epochs=18137
Reading HOLDOUT-SUBJECT validation...
  validation.csv: chunk 5, usable epochs=9109
Reading HOLDOUT-SUBJECT holdout...
  holdout.csv: chunk 5, usable epochs=9042

Holdout subjects verified: 25
holdout_subjects 1/25 sub-032 saved | train/val/hold=735/363/360 | PCs=20
holdout_subjects 2/25 sub-033 saved | train/val/hold=727/371/360 | PCs=20
holdout_subjects 3/25 sub-039 saved | train/val/hold=734/366/358 | PCs=20
holdout_subjects 4/25 sub-040 saved | train/val/hold=721/374/363 | PCs=20
holdout_subjects 5/25 sub-041 saved | train/val/hold=731/368/359 | PCs=20
holdout_subjects 6/25 sub-046 saved | train/val/hold=723/366/369 | PCs=20
holdout_subjects 7/25 sub-047 saved | train/val/hold=728/368/362 | PCs=20
holdout_subjects 8/25 sub-049 saved | train/val/hold=737/361/360 | PCs=20
holdout_subjects 9/25 sub-050 saved | train/val/hold=731/365/362 | PCs=20
holdout_subjects 10/25 sub-057 saved | train/val/hold=727/370/361 | PCs=20
holdout_subjects 11/25 sub-060 saved | train/val/hold=722/369/367 | PCs=20
holdout_subjects 12/25 sub-061 saved | train/val/hold=734/354/370 | PCs=20
holdout_subjects 13/25 sub-063 saved | train/val/hold=744/356/358 | PCs=20
holdout_subjects 14/25 sub-064 saved | train/val/hold=718/373/367 | PCs=20
holdout_subjects 15/25 sub-071 saved | train/val/hold=733/365/360 | PCs=20
holdout_subjects 16/25 sub-072 saved | train/val/hold=744/355/359 | PCs=20
holdout_subjects 17/25 sub-075 saved | train/val/hold=730/365/363 | PCs=20
holdout_subjects 18/25 sub-078 saved | train/val/hold=725/364/369 | PCs=20
holdout_subjects 19/25 sub-082 saved | train/val/hold=724/367/367 | PCs=20
holdout_subjects 20/25 sub-084 saved | train/val/hold=730/366/362 | PCs=20
holdout_subjects 21/25 sub-086 saved | train/val/hold=719/368/371 | PCs=20
holdout_subjects 22/25 sub-089 saved | train/val/hold=725/366/367 | PCs=20
holdout_subjects 23/25 sub-092 saved | train/val/hold=720/377/361 | PCs=20
holdout_subjects 24/25 sub-094 saved | train/val/hold=651/325/320 | PCs=20
holdout_subjects 25/25 sub-098 saved | train/val/hold=724/367/367 | PCs=20

3C COMPLETE — saved PCA outputs to: /content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3C_PCA_Outputs_Clean
Manifest: /content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3C_PCA_Outputs_Clean/pca_manifest.csv

## 3D — KNN + Logistic + SVM using the SAVED PCA outputs

3D does not recompute PCA. Each subject gets its own three models. It saves MAE, Spearman, accuracy, and epoch-level target/predictions.

In [ ]:
dev_metrics, dev_predictions, dev_paths = run_models_from_saved_pca(
    pca_output_folder=PCA_OUTPUT_FOLDER,
    output_folder=RESULTS_FOLDER,
    subject_group='development',
)

display(dev_metrics.groupby(['model','split'])[['accuracy','mae','spearman']].mean().round(4))
display(dev_predictions.head(20))
print(dev_paths)

development: subject 1/40 sub-034 complete
development: subject 2/40 sub-035 complete
development: subject 3/40 sub-036 complete
development: subject 4/40 sub-038 complete
development: subject 5/40 sub-042 complete
development: subject 6/40 sub-043 complete
development: subject 7/40 sub-044 complete
development: subject 8/40 sub-045 complete
development: subject 9/40 sub-048 complete
development: subject 10/40 sub-051 complete
development: subject 11/40 sub-052 complete
development: subject 12/40 sub-053 complete
development: subject 13/40 sub-054 complete
development: subject 14/40 sub-055 complete
development: subject 15/40 sub-056 complete
development: subject 16/40 sub-058 complete
development: subject 17/40 sub-059 complete
development: subject 18/40 sub-062 complete
development: subject 19/40 sub-065 complete
development: subject 20/40 sub-067 complete
development: subject 21/40 sub-068 complete
development: subject 22/40 sub-069 complete
development: subject 23/40 sub-070 complete
development: subject 24/40 sub-073 complete
development: subject 25/40 sub-074 complete
development: subject 26/40 sub-076 complete
development: subject 27/40 sub-077 complete
development: subject 28/40 sub-079 complete
development: subject 29/40 sub-080 complete
development: subject 30/40 sub-081 complete
development: subject 31/40 sub-083 complete
development: subject 32/40 sub-085 complete
development: subject 33/40 sub-087 complete
development: subject 34/40 sub-088 complete
development: subject 35/40 sub-090 complete
development: subject 36/40 sub-091 complete
development: subject 37/40 sub-093 complete
development: subject 38/40 sub-095 complete
development: subject 39/40 sub-096 complete
development: subject 40/40 sub-097 complete

                                accuracy     mae  spearman
model               split
KNN                 holdout       0.1044  3.3148    0.0950
                    train         1.0000  0.0000    1.0000
                    validation    0.1014  3.3181    0.0928
Logistic Regression holdout       0.0876  4.1681    0.1203
                    train         0.1818  3.7986    0.2083
                    validation    0.0840  4.2075    0.1062
SVM                 holdout       0.1129  2.7486    0.2051
                    train         0.1788  2.4456    0.4521
                    validation    0.1083  2.7475    0.2102

model,subject_id,subject_group,split,epoch_uid,target,knn_prediction,logistic_prediction,svm_prediction
0,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_0,1.0,3.0,1.0,4.095531
1,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_10,2.0,3.0,7.0,4.420955
2,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_100,10.0,3.0,8.0,4.949632
3,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_101,11.0,1.0,4.0,4.770509
4,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1012,4.0,3.0,10.0,4.432783
5,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1022,1.0,3.0,3.0,3.568767
6,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1023,2.0,4.0,2.0,3.287990
7,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1024,3.0,5.0,11.0,6.145371
8,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1029,8.0,5.0,13.0,6.027581
9,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1030,9.0,8.0,8.0,7.664953
10,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1045,2.0,2.0,3.0,4.014222
11,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1047,4.0,4.0,4.0,2.753844
12,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_105,2.0,3.0,12.0,3.823584
13,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1053,1.0,5.0,13.0,6.926977
14,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1054,2.0,3.0,2.0,4.573957
15,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1057,5.0,1.0,2.0,3.737505
16,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_106,3.0,3.0,12.0,3.842277
17,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1060,8.0,4.0,11.0,4.331342
18,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1064,12.0,3.0,3.0,3.069165
19,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1066,1.0,6.0,2.0,3.592792

{'metrics': PosixPath('/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/development_metrics.csv'), 'predictions_long': PosixPath('/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/development_epoch_predictions_long.csv'), 'predictions_wide': PosixPath('/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/development_epoch_predictions_wide.csv'), 'summary': PosixPath('/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/development_summary.csv')}

## Final 25 holdout subjects — run only after hyperparameters are fixed

When you are ready, set `INCLUDE_FINAL_25_IN_3C = True`, rerun the 3C cell once so their PCA files are saved, then run the cell below.

In [ ]:
# FINAL 25 SUBJECTS

final_metrics, final_predictions, final_paths = run_models_from_saved_pca(
    pca_output_folder=PCA_OUTPUT_FOLDER,
    output_folder=RESULTS_FOLDER,
    subject_group='holdout_subjects',
)

display(
    final_metrics.groupby(['model','split'])[
        ['accuracy','mae','spearman']
    ].mean().round(4)
)

display(final_predictions.head(20))

print(final_paths)

all_six_path, all_six = combine_all_six_predictions(
    RESULTS_FOLDER
)

print('All six datasets saved to:', all_six_path)

display(all_six.head(20))

holdout_subjects: subject 1/25 sub-032 complete
holdout_subjects: subject 2/25 sub-033 complete
holdout_subjects: subject 3/25 sub-039 complete
holdout_subjects: subject 4/25 sub-040 complete
holdout_subjects: subject 5/25 sub-041 complete
holdout_subjects: subject 6/25 sub-046 complete
holdout_subjects: subject 7/25 sub-047 complete
holdout_subjects: subject 8/25 sub-049 complete
holdout_subjects: subject 9/25 sub-050 complete
holdout_subjects: subject 10/25 sub-057 complete
holdout_subjects: subject 11/25 sub-060 complete
holdout_subjects: subject 12/25 sub-061 complete
holdout_subjects: subject 13/25 sub-063 complete
holdout_subjects: subject 14/25 sub-064 complete
holdout_subjects: subject 15/25 sub-071 complete
holdout_subjects: subject 16/25 sub-072 complete
holdout_subjects: subject 17/25 sub-075 complete
holdout_subjects: subject 18/25 sub-078 complete
holdout_subjects: subject 19/25 sub-082 complete
holdout_subjects: subject 20/25 sub-084 complete
holdout_subjects: subject 21/25 sub-086 complete
holdout_subjects: subject 22/25 sub-089 complete
holdout_subjects: subject 23/25 sub-092 complete
holdout_subjects: subject 24/25 sub-094 complete
holdout_subjects: subject 25/25 sub-098 complete

                                accuracy     mae  spearman
model               split
KNN                 holdout       0.1068  3.3340    0.0830
                    train         1.0000  0.0000    1.0000
                    validation    0.1038  3.3475    0.0660
Logistic Regression holdout       0.0829  4.2094    0.1037
                    train         0.1798  3.8156    0.1911
                    validation    0.0828  4.2071    0.0956
SVM                 holdout       0.1085  2.7435    0.1992
                    train         0.1751  2.4653    0.4497
                    validation    0.1136  2.7529    0.1768

model,subject_id,subject_group,split,epoch_uid,target,knn_prediction,logistic_prediction,svm_prediction
0,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_0,1.0,9.0,9.0,5.208862
1,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1002,4.0,6.0,6.0,5.395505
2,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1005,7.0,5.0,13.0,5.503550
3,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_101,7.0,7.0,8.0,7.421311
4,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1011,13.0,5.0,8.0,8.101250
5,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1019,3.0,4.0,11.0,5.647083
6,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1020,4.0,1.0,2.0,4.421605
7,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1022,1.0,2.0,11.0,3.190446
8,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1023,2.0,1.0,1.0,2.220226
9,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1024,3.0,4.0,11.0,6.097570
10,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1028,7.0,4.0,2.0,4.839148
11,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1029,8.0,3.0,13.0,5.764583
12,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_103,9.0,7.0,9.0,7.445170
13,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1042,8.0,4.0,6.0,5.646874
14,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1044,1.0,3.0,1.0,5.294298
15,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1048,5.0,7.0,12.0,7.000843
16,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_105,11.0,5.0,9.0,6.744378
17,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1052,9.0,6.0,12.0,5.999866
18,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_106,12.0,7.0,12.0,8.149769
19,32,holdout_subjects,holdout,032__sub-032_task-memory_eeg__digit_epoch_1060,3.0,5.0,5.0,3.602810

{'metrics': PosixPath('/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/holdout_subjects_metrics.csv'), 'predictions_long': PosixPath('/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/holdout_subjects_epoch_predictions_long.csv'), 'predictions_wide': PosixPath('/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/holdout_subjects_epoch_predictions_wide.csv'), 'summary': PosixPath('/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/holdout_subjects_summary.csv')}
All six datasets saved to: /content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/all_six_datasets_epoch_predictions.csv

,subject_id,subject_group,split,epoch_uid,target,knn_prediction,logistic_prediction,svm_prediction
0,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_0,1.0,3.0,1.0,4.095531
1,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_10,2.0,3.0,7.0,4.420955
2,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_100,10.0,3.0,8.0,4.949632
3,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_101,11.0,1.0,4.0,4.770509
4,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1012,4.0,3.0,10.0,4.432783
5,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1022,1.0,3.0,3.0,3.568767
6,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1023,2.0,4.0,2.0,3.287990
7,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1024,3.0,5.0,11.0,6.145371
8,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1029,8.0,5.0,13.0,6.027581
9,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1030,9.0,8.0,8.0,7.664953
10,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1045,2.0,2.0,3.0,4.014222
11,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1047,4.0,4.0,4.0,2.753844
12,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_105,2.0,3.0,12.0,3.823584
13,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1053,1.0,5.0,13.0,6.926977
14,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1054,2.0,3.0,2.0,4.573957
15,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1057,5.0,1.0,2.0,3.737505
16,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_106,3.0,3.0,12.0,3.842277
17,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1060,8.0,4.0,11.0,4.331342
18,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1064,12.0,3.0,3.0,3.069165
19,34,development,holdout,034__sub-034_task-memory_eeg__digit_epoch_1066,1.0,6.0,2.0,3.592792

In [ ]:
import pandas as pd

# ============================================================
# KNN — FOUR REQUIRED RESULT GROUPS
# ============================================================

all_metrics = pd.concat(
    [development_metrics, final_metrics],
    ignore_index=True
)

# KNN only
knn = all_metrics[
    all_metrics["model"] == "KNN"
].copy()

# Keep:
# development      -> train + validation
# holdout_subjects -> train + validation
knn = knn[
    (
        (knn["subject_group"] == "development")
        & (knn["split"].isin(["train", "validation"]))
    )
    |
    (
        (knn["subject_group"] == "holdout_subjects")
        & (knn["split"].isin(["train", "validation"]))
    )
].copy()


# ============================================================
# FRIENDLY NAMES
# ============================================================

def make_label(row):

    if (
        row["subject_group"] == "development"
        and row["split"] == "train"
    ):
        return "Training samples on training subjects"

    if (
        row["subject_group"] == "development"
        and row["split"] == "validation"
    ):
        return "Validation samples on training subjects"

    if (
        row["subject_group"] == "holdout_subjects"
        and row["split"] == "train"
    ):
        return "Training samples on holdout subjects"

    if (
        row["subject_group"] == "holdout_subjects"
        and row["split"] == "validation"
    ):
        return "Validation samples on holdout subjects"


knn["result_group"] = knn.apply(
    make_label,
    axis=1
)


# ============================================================
# SUMMARY
# ============================================================

order = [
    "Training samples on training subjects",
    "Validation samples on training subjects",
    "Training samples on holdout subjects",
    "Validation samples on holdout subjects",
]

summary = (
    knn
    .groupby("result_group")[
        ["accuracy", "mae", "spearman"]
    ]
    .mean()
    .reindex(order)
    .round(4)
)

print("=" * 80)
print("KNN — FOUR REQUIRED RESULTS")
print("=" * 80)

display(summary)


# ============================================================
# SUBJECT-BY-SUBJECT RESULTS
# ============================================================

subject_results = knn[
    [
        "subject_id",
        "result_group",
        "accuracy",
        "mae",
        "spearman",
    ]
].copy()

subject_results["result_group"] = pd.Categorical(
    subject_results["result_group"],
    categories=order,
    ordered=True
)

subject_results = subject_results.sort_values(
    ["result_group", "subject_id"]
)

print("\nSUBJECT-BY-SUBJECT KNN RESULTS")
display(subject_results)

================================================================================
KNN — FOUR REQUIRED RESULTS
================================================================================

                                         accuracy     mae  spearman
result_group
Training samples on training subjects      1.0000  0.0000    1.0000
Validation samples on training subjects    0.1014  3.3181    0.0928
Training samples on holdout subjects       1.0000  0.0000    1.0000
Validation samples on holdout subjects     0.1038  3.3475    0.0660

SUBJECT-BY-SUBJECT KNN RESULTS

,subject_id,result_group,accuracy,mae,spearman
0,34,Training samples on training subjects,1.000000,0.000000,1.000000
9,35,Training samples on training subjects,1.000000,0.000000,1.000000
18,36,Training samples on training subjects,1.000000,0.000000,1.000000
27,38,Training samples on training subjects,1.000000,0.000000,1.000000
36,42,Training samples on training subjects,1.000000,0.000000,1.000000
...,...,...,...,...,...
541,86,Validation samples on holdout subjects,0.100543,3.230978,0.121421
550,89,Validation samples on holdout subjects,0.098361,3.311476,0.069666
559,92,Validation samples on holdout subjects,0.106101,3.419098,0.052626
568,94,Validation samples on holdout subjects,0.104615,3.110769,0.050839
577,98,Validation samples on holdout subjects,0.111717,3.583106,0.001862

In [ ]:
import pandas as pd

all_metrics = pd.concat(
    [dev_metrics, final_metrics],
    ignore_index=True
)
# SVM only
svm = all_metrics[
    all_metrics["model"] == "SVM"
].copy()

# Keep the four requested combinations
svm = svm[
    (
        (svm["subject_group"] == "development")
        & (svm["split"].isin(["train", "validation"]))
    )
    |
    (
        (svm["subject_group"] == "holdout_subjects")
        & (svm["split"].isin(["train", "validation"]))
    )
].copy()


def make_label(row):

    if (
        row["subject_group"] == "development"
        and row["split"] == "train"
    ):
        return "Training samples on training subjects"

    if (
        row["subject_group"] == "development"
        and row["split"] == "validation"
    ):
        return "Validation samples on training subjects"

    if (
        row["subject_group"] == "holdout_subjects"
        and row["split"] == "train"
    ):
        return "Training samples on holdout subjects"

    if (
        row["subject_group"] == "holdout_subjects"
        and row["split"] == "validation"
    ):
        return "Validation samples on holdout subjects"


svm["result_group"] = svm.apply(
    make_label,
    axis=1
)

order = [
    "Training samples on training subjects",
    "Validation samples on training subjects",
    "Training samples on holdout subjects",
    "Validation samples on holdout subjects",
]

# ============================================================
# SUMMARY
# ============================================================

summary = (
    svm
    .groupby("result_group")[
        ["accuracy", "mae", "spearman"]
    ]
    .mean()
    .reindex(order)
    .round(4)
)

print("=" * 80)
print("SVM — FOUR REQUIRED RESULTS")
print("=" * 80)

display(summary)


# ============================================================
# SUBJECT-BY-SUBJECT
# ============================================================

subject_results = svm[
    [
        "subject_id",
        "result_group",
        "accuracy",
        "mae",
        "spearman",
    ]
].copy()

subject_results["result_group"] = pd.Categorical(
    subject_results["result_group"],
    categories=order,
    ordered=True
)

subject_results = subject_results.sort_values(
    ["result_group", "subject_id"]
)

print("\nSUBJECT-BY-SUBJECT SVM RESULTS")
display(subject_results)

================================================================================
SVM — FOUR REQUIRED RESULTS
================================================================================

                                         accuracy     mae  spearman
result_group
Training samples on training subjects      0.1788  2.4456    0.4521
Validation samples on training subjects    0.1083  2.7475    0.2102
Training samples on holdout subjects       0.1751  2.4653    0.4497
Validation samples on holdout subjects     0.1136  2.7529    0.1768

SUBJECT-BY-SUBJECT SVM RESULTS

,subject_id,result_group,accuracy,mae,spearman
6,34,Training samples on training subjects,0.197817,2.319301,0.504701
15,35,Training samples on training subjects,0.174625,2.325275,0.549067
24,36,Training samples on training subjects,0.175676,2.499698,0.438012
33,38,Training samples on training subjects,0.159944,2.544432,0.334128
42,42,Training samples on training subjects,0.141304,2.562253,0.357076
...,...,...,...,...,...
547,86,Validation samples on holdout subjects,0.089674,2.704958,0.246161
556,89,Validation samples on holdout subjects,0.139344,2.608256,0.267665
565,92,Validation samples on holdout subjects,0.071618,2.951894,0.097474
574,94,Validation samples on holdout subjects,0.104615,2.809646,0.101492
583,98,Validation samples on holdout subjects,0.122616,2.767704,0.177324

In [ ]:
from pathlib import Path
import pandas as pd

RESULTS_FOLDER = Path(
    "/content/drive/MyDrive/EEG Shared/Results/Luke/"
    "3D_Models_From_Clean_PCA"
)

# Load already-saved development results
development_metrics = pd.read_csv(
    RESULTS_FOLDER / "development_metrics.csv"
)

# Load final-25 results if they have already been run/saved
final_metrics_path = RESULTS_FOLDER / "holdout_subjects_metrics.csv"

if final_metrics_path.exists():
    final_metrics = pd.read_csv(final_metrics_path)
    print("Development + final metrics loaded.")
else:
    print("Development metrics loaded.")
    print("Final 25 metrics do not exist yet — run the final 25 models first.")

print("Development rows:", len(development_metrics))

if "final_metrics" in globals():
    print("Final rows:", len(final_metrics))

Development + final metrics loaded.
Development rows: 360
Final rows: 225

In [ ]:
from pathlib import Path
from itertools import product

import numpy as np
import pandas as pd

from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error
from scipy.stats import spearmanr


# ============================================================
# SVR + SAVED PCA TUNING
#
# ONLY DEVELOPMENT SUBJECTS ARE USED.
#
# Fit:        subject's TRAIN samples
# Select on:  subject's VALIDATION samples
#
# DO NOT use holdout subjects to choose hyperparameters.
# ============================================================


# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

PCA_OUTPUT_FOLDER = Path(
    "/content/drive/MyDrive/EEG Shared/Processed_data/"
    "Kosachenko_All_Subjects/3C_PCA_Outputs_Clean"
)

RESULTS_FOLDER = Path(
    "/content/drive/MyDrive/EEG Shared/Results/Luke/"
    "3D_Models_From_Clean_PCA"
)

RESULTS_FOLDER.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# HYPERPARAMETER SEARCH SPACE
# ------------------------------------------------------------

PC_COUNTS = [
    5,
    10,
    15,
    20,
]

C_VALUES = [
    0.1,
    1.0,
    10.0,
    100.0,
]

GAMMA_VALUES = [
    "scale",
    0.01,
    0.1,
]

EPSILON_VALUES = [
    0.05,
    0.1,
    0.5,
]


# ============================================================
# HELPERS
# ============================================================

def normalize_subject_id(value):

    s = str(value).strip()

    if s.endswith(".0"):
        s = s[:-2]

    if s.isdigit():
        return str(int(s))

    return s


def safe_spearman(y_true, y_pred):

    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    if len(y_true) < 2:
        return np.nan

    if np.all(y_true == y_true[0]):
        return np.nan

    if np.all(y_pred == y_pred[0]):
        return np.nan

    return float(
        spearmanr(
            y_true,
            y_pred
        ).statistic
    )


# ============================================================
# FIND ALL SAVED DEVELOPMENT SUBJECTS DIRECTLY FROM DRIVE
# ============================================================

development_folder = (
    PCA_OUTPUT_FOLDER /
    "development"
)

subject_files = sorted(
    development_folder.glob(
        "sub-*/pca_outputs.npz"
    ),
    key=lambda p: int(
        p.parent.name.replace(
            "sub-",
            ""
        )
    )
)


print(
    "Development PCA files found:",
    len(subject_files)
)


if len(subject_files) != 40:

    raise RuntimeError(
        f"Expected 40 development PCA files, "
        f"found {len(subject_files)}"
    )


subjects = []

for path in subject_files:

    subject_id = normalize_subject_id(
        path.parent.name.replace(
            "sub-",
            ""
        )
    )

    subjects.append(
        subject_id
    )


print(
    "Subjects:",
    [x.zfill(3) for x in subjects]
)


# ============================================================
# LOAD ALL DEVELOPMENT PCA DATA ONCE
#
# These files are small compared with the original CSVs,
# so this avoids repeatedly reading from Google Drive
# for every hyperparameter combination.
# ============================================================

subject_data = {}


for i, (
    subject,
    path
) in enumerate(
    zip(
        subjects,
        subject_files
    ),
    start=1
):

    data = np.load(
        path,
        allow_pickle=True
    )


    X_train = np.asarray(
        data["X_train_pca"],
        dtype=np.float32
    )

    y_train = np.asarray(
        data["y_train"],
        dtype=np.float32
    )


    X_validation = np.asarray(
        data["X_validation_pca"],
        dtype=np.float32
    )

    y_validation = np.asarray(
        data["y_validation"],
        dtype=np.float32
    )


    if len(X_train) == 0:
        raise RuntimeError(
            f"Subject {subject} "
            f"has empty training data."
        )


    if len(X_validation) == 0:
        raise RuntimeError(
            f"Subject {subject} "
            f"has empty validation data."
        )


    subject_data[
        subject
    ] = {
        "X_train":
            X_train,

        "y_train":
            y_train,

        "X_validation":
            X_validation,

        "y_validation":
            y_validation,
    }


    print(
        f"Loaded {i}/40 "
        f"sub-{subject.zfill(3)} | "
        f"train={len(X_train)} | "
        f"validation={len(X_validation)} | "
        f"saved PCs={X_train.shape[1]}"
    )


# ============================================================
# VERIFY MAXIMUM AVAILABLE PCA COMPONENTS
# ============================================================

min_saved_pc_count = min(
    d["X_train"].shape[1]
    for d in subject_data.values()
)


print(
    "\nMinimum saved PCs across subjects:",
    min_saved_pc_count
)


invalid_pc_counts = [
    n
    for n in PC_COUNTS
    if n > min_saved_pc_count
]


if invalid_pc_counts:

    raise RuntimeError(
        f"Requested PC counts "
        f"{invalid_pc_counts}, "
        f"but only "
        f"{min_saved_pc_count} "
        f"components are available "
        f"for every subject."
    )


# ============================================================
# CREATE ALL COMBINATIONS
# ============================================================

combinations = list(
    product(
        PC_COUNTS,
        C_VALUES,
        GAMMA_VALUES,
        EPSILON_VALUES,
    )
)


print(
    "\nCombinations:",
    len(combinations)
)

print(
    "Subjects per combination:",
    len(subjects)
)

print(
    "Total SVR fits:",
    len(combinations)
    *
    len(subjects)
)

print(
    "\nStarting tuning...\n"
)


# ============================================================
# TUNING LOOP
# ============================================================

result_rows = []

subject_result_rows = []


for combo_number, (
    pc_count,
    C,
    gamma,
    epsilon,
) in enumerate(
    combinations,
    start=1
):


    combo_spearman = []
    combo_mae = []
    combo_accuracy = []


    for subject in subjects:

        d = subject_data[
            subject
        ]


        # ----------------------------------------------------
        # KEEP ONLY FIRST N PCA COMPONENTS
        # ----------------------------------------------------

        X_train = (
            d["X_train"][
                :,
                :pc_count
            ]
        )

        X_validation = (
            d["X_validation"][
                :,
                :pc_count
            ]
        )

        y_train = d[
            "y_train"
        ]

        y_validation = d[
            "y_validation"
        ]


        # ----------------------------------------------------
        # FIT SVR
        # ----------------------------------------------------

        model = SVR(
            kernel="rbf",
            C=C,
            gamma=gamma,
            epsilon=epsilon,
        )


        model.fit(
            X_train,
            y_train
        )


        # ----------------------------------------------------
        # VALIDATION
        # ----------------------------------------------------

        prediction = (
            model.predict(
                X_validation
            )
        )


        rho = safe_spearman(
            y_validation,
            prediction
        )


        mae = float(
            mean_absolute_error(
                y_validation,
                prediction
            )
        )


        # Rounded exact-match accuracy
        rounded_prediction = np.clip(
            np.rint(
                prediction
            ),
            1,
            13
        ).astype(int)


        accuracy = float(
            np.mean(
                rounded_prediction
                ==
                y_validation.astype(int)
            )
        )


        if not np.isnan(rho):

            combo_spearman.append(
                rho
            )


        combo_mae.append(
            mae
        )

        combo_accuracy.append(
            accuracy
        )


        # Save subject-level tuning result
        subject_result_rows.append(
            {
                "pc_count":
                    pc_count,

                "C":
                    C,

                "gamma":
                    gamma,

                "epsilon":
                    epsilon,

                "subject_id":
                    subject,

                "validation_spearman":
                    rho,

                "validation_mae":
                    mae,

                "validation_accuracy":
                    accuracy,
            }
        )


    # ========================================================
    # AGGREGATE ACROSS 40 SUBJECTS
    # ========================================================

    mean_spearman = float(
        np.nanmean(
            combo_spearman
        )
    )

    median_spearman = float(
        np.nanmedian(
            combo_spearman
        )
    )

    mean_mae = float(
        np.mean(
            combo_mae
        )
    )

    mean_accuracy = float(
        np.mean(
            combo_accuracy
        )
    )


    result_rows.append(
        {
            "pc_count":
                pc_count,

            "C":
                C,

            "gamma":
                gamma,

            "epsilon":
                epsilon,

            "mean_validation_spearman":
                mean_spearman,

            "median_validation_spearman":
                median_spearman,

            "mean_validation_mae":
                mean_mae,

            "mean_validation_accuracy":
                mean_accuracy,

            "subjects":
                len(subjects),
        }
    )


    print(
        f"{combo_number:3d}/"
        f"{len(combinations)} | "
        f"PC={pc_count:2d} | "
        f"C={C:<6} | "
        f"gamma={str(gamma):<6} | "
        f"eps={epsilon:<4} | "
        f"rho={mean_spearman:.4f} | "
        f"MAE={mean_mae:.4f} | "
        f"acc={mean_accuracy:.4f}"
    )


# ============================================================
# SUMMARY TABLE
# ============================================================

tuning_results = pd.DataFrame(
    result_rows
)


# PRIMARY:
# highest validation Spearman
#
# SECONDARY:
# lowest validation MAE

tuning_results = (
    tuning_results
    .sort_values(
        [
            "mean_validation_spearman",
            "mean_validation_mae",
        ],
        ascending=[
            False,
            True,
        ],
    )
    .reset_index(
        drop=True
    )
)


print(
    "\n"
    + "=" * 100
)

print(
    "TOP 20 SVR + PCA SETTINGS"
)

print(
    "=" * 100
)


display(
    tuning_results.head(20)
)


# ============================================================
# BEST RESULT
# ============================================================

best = tuning_results.iloc[0]


print(
    "\n"
    + "=" * 100
)

print(
    "BEST SETTINGS"
)

print(
    "=" * 100
)


print(
    "PC count:",
    int(
        best[
            "pc_count"
        ]
    )
)

print(
    "C:",
    best["C"]
)

print(
    "gamma:",
    best["gamma"]
)

print(
    "epsilon:",
    best["epsilon"]
)


print(
    "\nMean validation Spearman:",
    round(
        best[
            "mean_validation_spearman"
        ],
        4
    )
)

print(
    "Median validation Spearman:",
    round(
        best[
            "median_validation_spearman"
        ],
        4
    )
)

print(
    "Mean validation MAE:",
    round(
        best[
            "mean_validation_mae"
        ],
        4
    )
)

print(
    "Rounded validation accuracy:",
    round(
        best[
            "mean_validation_accuracy"
        ],
        4
    )
)


# ============================================================
# SAVE RESULTS
# ============================================================

summary_path = (
    RESULTS_FOLDER /
    "svr_pca_tuning_summary.csv"
)

subject_path = (
    RESULTS_FOLDER /
    "svr_pca_tuning_subject_results.csv"
)


tuning_results.to_csv(
    summary_path,
    index=False
)


pd.DataFrame(
    subject_result_rows
).to_csv(
    subject_path,
    index=False
)


print(
    "\nSaved tuning summary:"
)

print(
    summary_path
)


print(
    "\nSaved subject-level tuning results:"
)

print(
    subject_path
)

Development PCA files found: 40
Subjects: ['034', '035', '036', '038', '042', '043', '044', '045', '048', '051', '052', '053', '054', '055', '056', '058', '059', '062', '065', '067', '068', '069', '070', '073', '074', '076', '077', '079', '080', '081', '083', '085', '087', '088', '090', '091', '093', '095', '096', '097']
Loaded 1/40 sub-034 | train=733 | validation=359 | saved PCs=20
Loaded 2/40 sub-035 | train=733 | validation=367 | saved PCs=20
Loaded 3/40 sub-036 | train=740 | validation=358 | saved PCs=20
Loaded 4/40 sub-038 | train=719 | validation=370 | saved PCs=20
Loaded 5/40 sub-042 | train=736 | validation=375 | saved PCs=20
Loaded 6/40 sub-043 | train=728 | validation=362 | saved PCs=20
Loaded 7/40 sub-044 | train=733 | validation=364 | saved PCs=20
Loaded 8/40 sub-045 | train=743 | validation=355 | saved PCs=20
Loaded 9/40 sub-048 | train=731 | validation=367 | saved PCs=20
Loaded 10/40 sub-051 | train=721 | validation=369 | saved PCs=20
Loaded 11/40 sub-052 | train=731 | validation=359 | saved PCs=20
Loaded 12/40 sub-053 | train=727 | validation=369 | saved PCs=20
Loaded 13/40 sub-054 | train=741 | validation=355 | saved PCs=20
Loaded 14/40 sub-055 | train=722 | validation=369 | saved PCs=20
Loaded 15/40 sub-056 | train=728 | validation=367 | saved PCs=20
Loaded 16/40 sub-058 | train=740 | validation=358 | saved PCs=20
Loaded 17/40 sub-059 | train=721 | validation=364 | saved PCs=20
Loaded 18/40 sub-062 | train=733 | validation=364 | saved PCs=20
Loaded 19/40 sub-065 | train=725 | validation=370 | saved PCs=20
Loaded 20/40 sub-067 | train=736 | validation=363 | saved PCs=20
Loaded 21/40 sub-068 | train=716 | validation=372 | saved PCs=20
Loaded 22/40 sub-069 | train=716 | validation=371 | saved PCs=20
Loaded 23/40 sub-070 | train=732 | validation=358 | saved PCs=20
Loaded 24/40 sub-073 | train=729 | validation=360 | saved PCs=20
Loaded 25/40 sub-074 | train=717 | validation=374 | saved PCs=20
Loaded 26/40 sub-076 | train=743 | validation=356 | saved PCs=20
Loaded 27/40 sub-077 | train=719 | validation=365 | saved PCs=20
Loaded 28/40 sub-079 | train=729 | validation=370 | saved PCs=20
Loaded 29/40 sub-080 | train=733 | validation=365 | saved PCs=20
Loaded 30/40 sub-081 | train=745 | validation=354 | saved PCs=20
Loaded 31/40 sub-083 | train=724 | validation=372 | saved PCs=20
Loaded 32/40 sub-085 | train=736 | validation=360 | saved PCs=20
Loaded 33/40 sub-087 | train=730 | validation=361 | saved PCs=20
Loaded 34/40 sub-088 | train=735 | validation=366 | saved PCs=20
Loaded 35/40 sub-090 | train=745 | validation=354 | saved PCs=20
Loaded 36/40 sub-091 | train=721 | validation=367 | saved PCs=20
Loaded 37/40 sub-093 | train=729 | validation=369 | saved PCs=20
Loaded 38/40 sub-095 | train=720 | validation=365 | saved PCs=20
Loaded 39/40 sub-096 | train=721 | validation=366 | saved PCs=20
Loaded 40/40 sub-097 | train=734 | validation=365 | saved PCs=20

Minimum saved PCs across subjects: 20

Combinations: 144
Subjects per combination: 40
Total SVR fits: 5760

Starting tuning...

  1/144 | PC= 5 | C=0.1    | gamma=scale  | eps=0.05 | rho=0.1497 | MAE=2.7925 | acc=0.1148
  2/144 | PC= 5 | C=0.1    | gamma=scale  | eps=0.1  | rho=0.1478 | MAE=2.7932 | acc=0.1148
  3/144 | PC= 5 | C=0.1    | gamma=scale  | eps=0.5  | rho=0.1399 | MAE=2.8009 | acc=0.1127
  4/144 | PC= 5 | C=0.1    | gamma=0.01   | eps=0.05 | rho=0.1467 | MAE=2.8020 | acc=0.1125
  5/144 | PC= 5 | C=0.1    | gamma=0.01   | eps=0.1  | rho=0.1481 | MAE=2.8019 | acc=0.1125
  6/144 | PC= 5 | C=0.1    | gamma=0.01   | eps=0.5  | rho=0.1462 | MAE=2.8074 | acc=0.1125
  7/144 | PC= 5 | C=0.1    | gamma=0.1    | eps=0.05 | rho=0.0814 | MAE=2.8160 | acc=0.1129
  8/144 | PC= 5 | C=0.1    | gamma=0.1    | eps=0.1  | rho=0.0815 | MAE=2.8207 | acc=0.1130
  9/144 | PC= 5 | C=0.1    | gamma=0.1    | eps=0.5  | rho=0.0834 | MAE=2.8601 | acc=0.1125
 10/144 | PC= 5 | C=1.0    | gamma=scale  | eps=0.05 | rho=0.1620 | MAE=2.7866 | acc=0.1072
 11/144 | PC= 5 | C=1.0    | gamma=scale  | eps=0.1  | rho=0.1627 | MAE=2.7858 | acc=0.1076
 12/144 | PC= 5 | C=1.0    | gamma=scale  | eps=0.5  | rho=0.1622 | MAE=2.7857 | acc=0.1065
 13/144 | PC= 5 | C=1.0    | gamma=0.01   | eps=0.05 | rho=0.1507 | MAE=2.8038 | acc=0.1068
 14/144 | PC= 5 | C=1.0    | gamma=0.01   | eps=0.1  | rho=0.1512 | MAE=2.8032 | acc=0.1064
 15/144 | PC= 5 | C=1.0    | gamma=0.01   | eps=0.5  | rho=0.1568 | MAE=2.7965 | acc=0.1088
 16/144 | PC= 5 | C=1.0    | gamma=0.1    | eps=0.05 | rho=0.0818 | MAE=2.8254 | acc=0.1105
 17/144 | PC= 5 | C=1.0    | gamma=0.1    | eps=0.1  | rho=0.0826 | MAE=2.8253 | acc=0.1105
 18/144 | PC= 5 | C=1.0    | gamma=0.1    | eps=0.5  | rho=0.0836 | MAE=2.8256 | acc=0.1105
 19/144 | PC= 5 | C=10.0   | gamma=scale  | eps=0.05 | rho=0.1519 | MAE=2.8343 | acc=0.1062
 20/144 | PC= 5 | C=10.0   | gamma=scale  | eps=0.1  | rho=0.1523 | MAE=2.8334 | acc=0.1061
 21/144 | PC= 5 | C=10.0   | gamma=scale  | eps=0.5  | rho=0.1558 | MAE=2.8231 | acc=0.1058
 22/144 | PC= 5 | C=10.0   | gamma=0.01   | eps=0.05 | rho=0.1222 | MAE=2.9759 | acc=0.1072
 23/144 | PC= 5 | C=10.0   | gamma=0.01   | eps=0.1  | rho=0.1222 | MAE=2.9738 | acc=0.1075
 24/144 | PC= 5 | C=10.0   | gamma=0.01   | eps=0.5  | rho=0.1195 | MAE=2.9619 | acc=0.1060
 25/144 | PC= 5 | C=10.0   | gamma=0.1    | eps=0.05 | rho=0.0589 | MAE=2.9987 | acc=0.0938
 26/144 | PC= 5 | C=10.0   | gamma=0.1    | eps=0.1  | rho=0.0589 | MAE=2.9967 | acc=0.0928
 27/144 | PC= 5 | C=10.0   | gamma=0.1    | eps=0.5  | rho=0.0589 | MAE=2.9829 | acc=0.0902
 28/144 | PC= 5 | C=100.0  | gamma=scale  | eps=0.05 | rho=0.1333 | MAE=2.9800 | acc=0.1002
 29/144 | PC= 5 | C=100.0  | gamma=scale  | eps=0.1  | rho=0.1346 | MAE=2.9758 | acc=0.1002
 30/144 | PC= 5 | C=100.0  | gamma=scale  | eps=0.5  | rho=0.1364 | MAE=2.9593 | acc=0.1028
 31/144 | PC= 5 | C=100.0  | gamma=0.01   | eps=0.05 | rho=0.0729 | MAE=3.4651 | acc=0.0989
 32/144 | PC= 5 | C=100.0  | gamma=0.01   | eps=0.1  | rho=0.0736 | MAE=3.4564 | acc=0.0995
 33/144 | PC= 5 | C=100.0  | gamma=0.01   | eps=0.5  | rho=0.0766 | MAE=3.3934 | acc=0.0970
 34/144 | PC= 5 | C=100.0  | gamma=0.1    | eps=0.05 | rho=0.0512 | MAE=3.1304 | acc=0.0940
 35/144 | PC= 5 | C=100.0  | gamma=0.1    | eps=0.1  | rho=0.0512 | MAE=3.1250 | acc=0.0939
 36/144 | PC= 5 | C=100.0  | gamma=0.1    | eps=0.5  | rho=0.0514 | MAE=3.0857 | acc=0.0922
 37/144 | PC=10 | C=0.1    | gamma=scale  | eps=0.05 | rho=0.1646 | MAE=2.7879 | acc=0.1136
 38/144 | PC=10 | C=0.1    | gamma=scale  | eps=0.1  | rho=0.1641 | MAE=2.7886 | acc=0.1141
 39/144 | PC=10 | C=0.1    | gamma=scale  | eps=0.5  | rho=0.1570 | MAE=2.7958 | acc=0.1145
 40/144 | PC=10 | C=0.1    | gamma=0.01   | eps=0.05 | rho=0.1399 | MAE=2.8072 | acc=0.1123
 41/144 | PC=10 | C=0.1    | gamma=0.01   | eps=0.1  | rho=0.1406 | MAE=2.8083 | acc=0.1129
 42/144 | PC=10 | C=0.1    | gamma=0.01   | eps=0.5  | rho=0.1390 | MAE=2.8248 | acc=0.1119
 43/144 | PC=10 | C=0.1    | gamma=0.1    | eps=0.05 | rho=0.0782 | MAE=2.8201 | acc=0.1131
 44/144 | PC=10 | C=0.1    | gamma=0.1    | eps=0.1  | rho=0.0784 | MAE=2.8270 | acc=0.1131
 45/144 | PC=10 | C=0.1    | gamma=0.1    | eps=0.5  | rho=0.0809 | MAE=2.8693 | acc=0.1132
 46/144 | PC=10 | C=1.0    | gamma=scale  | eps=0.05 | rho=0.1807 | MAE=2.7679 | acc=0.1099
 47/144 | PC=10 | C=1.0    | gamma=scale  | eps=0.1  | rho=0.1814 | MAE=2.7678 | acc=0.1096
 48/144 | PC=10 | C=1.0    | gamma=scale  | eps=0.5  | rho=0.1851 | MAE=2.7665 | acc=0.1100
 49/144 | PC=10 | C=1.0    | gamma=0.01   | eps=0.05 | rho=0.1455 | MAE=2.8025 | acc=0.1078
 50/144 | PC=10 | C=1.0    | gamma=0.01   | eps=0.1  | rho=0.1459 | MAE=2.8020 | acc=0.1084
 51/144 | PC=10 | C=1.0    | gamma=0.01   | eps=0.5  | rho=0.1506 | MAE=2.7972 | acc=0.1082
 52/144 | PC=10 | C=1.0    | gamma=0.1    | eps=0.05 | rho=0.0784 | MAE=2.8231 | acc=0.1123
 53/144 | PC=10 | C=1.0    | gamma=0.1    | eps=0.1  | rho=0.0785 | MAE=2.8234 | acc=0.1124
 54/144 | PC=10 | C=1.0    | gamma=0.1    | eps=0.5  | rho=0.0820 | MAE=2.8263 | acc=0.1122
 55/144 | PC=10 | C=10.0   | gamma=scale  | eps=0.05 | rho=0.1654 | MAE=2.8485 | acc=0.1071
 56/144 | PC=10 | C=10.0   | gamma=scale  | eps=0.1  | rho=0.1664 | MAE=2.8465 | acc=0.1087
 57/144 | PC=10 | C=10.0   | gamma=scale  | eps=0.5  | rho=0.1721 | MAE=2.8339 | acc=0.1074
 58/144 | PC=10 | C=10.0   | gamma=0.01   | eps=0.05 | rho=0.1158 | MAE=2.9917 | acc=0.0995
 59/144 | PC=10 | C=10.0   | gamma=0.01   | eps=0.1  | rho=0.1160 | MAE=2.9888 | acc=0.1009
 60/144 | PC=10 | C=10.0   | gamma=0.01   | eps=0.5  | rho=0.1169 | MAE=2.9679 | acc=0.1006
 61/144 | PC=10 | C=10.0   | gamma=0.1    | eps=0.05 | rho=0.0723 | MAE=2.8809 | acc=0.0840
 62/144 | PC=10 | C=10.0   | gamma=0.1    | eps=0.1  | rho=0.0722 | MAE=2.8814 | acc=0.0838
 63/144 | PC=10 | C=10.0   | gamma=0.1    | eps=0.5  | rho=0.0716 | MAE=2.8870 | acc=0.0803
 64/144 | PC=10 | C=100.0  | gamma=scale  | eps=0.05 | rho=0.1271 | MAE=3.1317 | acc=0.1010
 65/144 | PC=10 | C=100.0  | gamma=scale  | eps=0.1  | rho=0.1279 | MAE=3.1261 | acc=0.1011
 66/144 | PC=10 | C=100.0  | gamma=scale  | eps=0.5  | rho=0.1361 | MAE=3.0821 | acc=0.1003
 67/144 | PC=10 | C=100.0  | gamma=0.01   | eps=0.05 | rho=0.0912 | MAE=3.3011 | acc=0.0951
 68/144 | PC=10 | C=100.0  | gamma=0.01   | eps=0.1  | rho=0.0916 | MAE=3.2930 | acc=0.0958
 69/144 | PC=10 | C=100.0  | gamma=0.01   | eps=0.5  | rho=0.0943 | MAE=3.2316 | acc=0.0992
 70/144 | PC=10 | C=100.0  | gamma=0.1    | eps=0.05 | rho=0.0724 | MAE=2.8815 | acc=0.0837
 71/144 | PC=10 | C=100.0  | gamma=0.1    | eps=0.1  | rho=0.0724 | MAE=2.8820 | acc=0.0834
 72/144 | PC=10 | C=100.0  | gamma=0.1    | eps=0.5  | rho=0.0719 | MAE=2.8874 | acc=0.0800
 73/144 | PC=15 | C=0.1    | gamma=scale  | eps=0.05 | rho=0.1782 | MAE=2.7858 | acc=0.1145
 74/144 | PC=15 | C=0.1    | gamma=scale  | eps=0.1  | rho=0.1776 | MAE=2.7863 | acc=0.1144
 75/144 | PC=15 | C=0.1    | gamma=scale  | eps=0.5  | rho=0.1686 | MAE=2.7925 | acc=0.1142
 76/144 | PC=15 | C=0.1    | gamma=0.01   | eps=0.05 | rho=0.1428 | MAE=2.8093 | acc=0.1134
 77/144 | PC=15 | C=0.1    | gamma=0.01   | eps=0.1  | rho=0.1409 | MAE=2.8116 | acc=0.1129
 78/144 | PC=15 | C=0.1    | gamma=0.01   | eps=0.5  | rho=0.1417 | MAE=2.8405 | acc=0.1121
 79/144 | PC=15 | C=0.1    | gamma=0.1    | eps=0.05 | rho=0.0793 | MAE=2.8206 | acc=0.1131
 80/144 | PC=15 | C=0.1    | gamma=0.1    | eps=0.1  | rho=0.0793 | MAE=2.8276 | acc=0.1131
 81/144 | PC=15 | C=0.1    | gamma=0.1    | eps=0.5  | rho=0.0845 | MAE=2.8701 | acc=0.1131
 82/144 | PC=15 | C=1.0    | gamma=scale  | eps=0.05 | rho=0.1972 | MAE=2.7572 | acc=0.1070
 83/144 | PC=15 | C=1.0    | gamma=scale  | eps=0.1  | rho=0.1979 | MAE=2.7569 | acc=0.1073
 84/144 | PC=15 | C=1.0    | gamma=scale  | eps=0.5  | rho=0.2000 | MAE=2.7549 | acc=0.1072
 85/144 | PC=15 | C=1.0    | gamma=0.01   | eps=0.05 | rho=0.1486 | MAE=2.7964 | acc=0.1100
 86/144 | PC=15 | C=1.0    | gamma=0.01   | eps=0.1  | rho=0.1491 | MAE=2.7961 | acc=0.1100
 87/144 | PC=15 | C=1.0    | gamma=0.01   | eps=0.5  | rho=0.1520 | MAE=2.7941 | acc=0.1105
 88/144 | PC=15 | C=1.0    | gamma=0.1    | eps=0.05 | rho=0.0830 | MAE=2.8246 | acc=0.1129
 89/144 | PC=15 | C=1.0    | gamma=0.1    | eps=0.1  | rho=0.0825 | MAE=2.8250 | acc=0.1129
 90/144 | PC=15 | C=1.0    | gamma=0.1    | eps=0.5  | rho=0.0857 | MAE=2.8280 | acc=0.1129
 91/144 | PC=15 | C=10.0   | gamma=scale  | eps=0.05 | rho=0.1798 | MAE=2.8472 | acc=0.1111
 92/144 | PC=15 | C=10.0   | gamma=scale  | eps=0.1  | rho=0.1801 | MAE=2.8458 | acc=0.1107
 93/144 | PC=15 | C=10.0   | gamma=scale  | eps=0.5  | rho=0.1847 | MAE=2.8302 | acc=0.1077
 94/144 | PC=15 | C=10.0   | gamma=0.01   | eps=0.05 | rho=0.1232 | MAE=2.9228 | acc=0.1041
 95/144 | PC=15 | C=10.0   | gamma=0.01   | eps=0.1  | rho=0.1234 | MAE=2.9214 | acc=0.1031
 96/144 | PC=15 | C=10.0   | gamma=0.01   | eps=0.5  | rho=0.1236 | MAE=2.9113 | acc=0.1030
 97/144 | PC=15 | C=10.0   | gamma=0.1    | eps=0.05 | rho=0.0763 | MAE=2.8801 | acc=0.0808
 98/144 | PC=15 | C=10.0   | gamma=0.1    | eps=0.1  | rho=0.0769 | MAE=2.8807 | acc=0.0794
 99/144 | PC=15 | C=10.0   | gamma=0.1    | eps=0.5  | rho=0.0724 | MAE=2.8874 | acc=0.0767
100/144 | PC=15 | C=100.0  | gamma=scale  | eps=0.05 | rho=0.1431 | MAE=3.1770 | acc=0.1021
101/144 | PC=15 | C=100.0  | gamma=scale  | eps=0.1  | rho=0.1438 | MAE=3.1712 | acc=0.1040
102/144 | PC=15 | C=100.0  | gamma=scale  | eps=0.5  | rho=0.1478 | MAE=3.1285 | acc=0.1055
103/144 | PC=15 | C=100.0  | gamma=0.01   | eps=0.05 | rho=0.1083 | MAE=3.0435 | acc=0.0992
104/144 | PC=15 | C=100.0  | gamma=0.01   | eps=0.1  | rho=0.1088 | MAE=3.0392 | acc=0.0996
105/144 | PC=15 | C=100.0  | gamma=0.01   | eps=0.5  | rho=0.1112 | MAE=3.0099 | acc=0.0986
106/144 | PC=15 | C=100.0  | gamma=0.1    | eps=0.05 | rho=0.0764 | MAE=2.8801 | acc=0.0809
107/144 | PC=15 | C=100.0  | gamma=0.1    | eps=0.1  | rho=0.0770 | MAE=2.8807 | acc=0.0794
108/144 | PC=15 | C=100.0  | gamma=0.1    | eps=0.5  | rho=0.0724 | MAE=2.8875 | acc=0.0767
109/144 | PC=20 | C=0.1    | gamma=scale  | eps=0.05 | rho=0.1878 | MAE=2.7855 | acc=0.1137
110/144 | PC=20 | C=0.1    | gamma=scale  | eps=0.1  | rho=0.1875 | MAE=2.7857 | acc=0.1136
111/144 | PC=20 | C=0.1    | gamma=scale  | eps=0.5  | rho=0.1759 | MAE=2.7914 | acc=0.1126
112/144 | PC=20 | C=0.1    | gamma=0.01   | eps=0.05 | rho=0.1482 | MAE=2.8109 | acc=0.1133
113/144 | PC=20 | C=0.1    | gamma=0.01   | eps=0.1  | rho=0.1476 | MAE=2.8145 | acc=0.1134
114/144 | PC=20 | C=0.1    | gamma=0.01   | eps=0.5  | rho=0.1469 | MAE=2.8490 | acc=0.1114
115/144 | PC=20 | C=0.1    | gamma=0.1    | eps=0.05 | rho=0.0798 | MAE=2.8207 | acc=0.1131
116/144 | PC=20 | C=0.1    | gamma=0.1    | eps=0.1  | rho=0.0798 | MAE=2.8277 | acc=0.1131
117/144 | PC=20 | C=0.1    | gamma=0.1    | eps=0.5  | rho=0.0838 | MAE=2.8702 | acc=0.1131
118/144 | PC=20 | C=1.0    | gamma=scale  | eps=0.05 | rho=0.2098 | MAE=2.7478 | acc=0.1080
119/144 | PC=20 | C=1.0    | gamma=scale  | eps=0.1  | rho=0.2102 | MAE=2.7475 | acc=0.1083
120/144 | PC=20 | C=1.0    | gamma=scale  | eps=0.5  | rho=0.2091 | MAE=2.7467 | acc=0.1088
121/144 | PC=20 | C=1.0    | gamma=0.01   | eps=0.05 | rho=0.1547 | MAE=2.7950 | acc=0.1101
122/144 | PC=20 | C=1.0    | gamma=0.01   | eps=0.1  | rho=0.1554 | MAE=2.7950 | acc=0.1099
123/144 | PC=20 | C=1.0    | gamma=0.01   | eps=0.5  | rho=0.1567 | MAE=2.7952 | acc=0.1100
124/144 | PC=20 | C=1.0    | gamma=0.1    | eps=0.05 | rho=0.0810 | MAE=2.8255 | acc=0.1129
125/144 | PC=20 | C=1.0    | gamma=0.1    | eps=0.1  | rho=0.0824 | MAE=2.8260 | acc=0.1129
126/144 | PC=20 | C=1.0    | gamma=0.1    | eps=0.5  | rho=0.0847 | MAE=2.8289 | acc=0.1129
127/144 | PC=20 | C=10.0   | gamma=scale  | eps=0.05 | rho=0.1920 | MAE=2.8428 | acc=0.1058
128/144 | PC=20 | C=10.0   | gamma=scale  | eps=0.1  | rho=0.1920 | MAE=2.8417 | acc=0.1059
129/144 | PC=20 | C=10.0   | gamma=scale  | eps=0.5  | rho=0.1938 | MAE=2.8301 | acc=0.1050
130/144 | PC=20 | C=10.0   | gamma=0.01   | eps=0.05 | rho=0.1274 | MAE=2.8792 | acc=0.1012
131/144 | PC=20 | C=10.0   | gamma=0.01   | eps=0.1  | rho=0.1273 | MAE=2.8789 | acc=0.1016
132/144 | PC=20 | C=10.0   | gamma=0.01   | eps=0.5  | rho=0.1277 | MAE=2.8775 | acc=0.0976
133/144 | PC=20 | C=10.0   | gamma=0.1    | eps=0.05 | rho=0.0739 | MAE=2.8822 | acc=0.0806
134/144 | PC=20 | C=10.0   | gamma=0.1    | eps=0.1  | rho=0.0743 | MAE=2.8828 | acc=0.0790
135/144 | PC=20 | C=10.0   | gamma=0.1    | eps=0.5  | rho=0.0748 | MAE=2.8894 | acc=0.0765
136/144 | PC=20 | C=100.0  | gamma=scale  | eps=0.05 | rho=0.1486 | MAE=3.1951 | acc=0.1053
137/144 | PC=20 | C=100.0  | gamma=scale  | eps=0.1  | rho=0.1493 | MAE=3.1888 | acc=0.1058
138/144 | PC=20 | C=100.0  | gamma=scale  | eps=0.5  | rho=0.1523 | MAE=3.1402 | acc=0.1062
139/144 | PC=20 | C=100.0  | gamma=0.01   | eps=0.05 | rho=0.1194 | MAE=2.9325 | acc=0.0992
140/144 | PC=20 | C=100.0  | gamma=0.01   | eps=0.1  | rho=0.1195 | MAE=2.9306 | acc=0.0993
141/144 | PC=20 | C=100.0  | gamma=0.01   | eps=0.5  | rho=0.1206 | MAE=2.9179 | acc=0.0971
142/144 | PC=20 | C=100.0  | gamma=0.1    | eps=0.05 | rho=0.0739 | MAE=2.8822 | acc=0.0806
143/144 | PC=20 | C=100.0  | gamma=0.1    | eps=0.1  | rho=0.0743 | MAE=2.8828 | acc=0.0790
144/144 | PC=20 | C=100.0  | gamma=0.1    | eps=0.5  | rho=0.0748 | MAE=2.8894 | acc=0.0765

====================================================================================================
TOP 20 SVR + PCA SETTINGS
====================================================================================================

,pc_count,C,gamma,epsilon,mean_validation_spearman,median_validation_spearman,mean_validation_mae,mean_validation_accuracy,subjects
0,20,1.0,scale,0.10,0.210212,0.205948,2.747458,0.108308,40
1,20,1.0,scale,0.05,0.209817,0.206450,2.747788,0.107950,40
2,20,1.0,scale,0.50,0.209124,0.216771,2.746677,0.108830,40
3,15,1.0,scale,0.50,0.199955,0.214312,2.754885,0.107249,40
4,15,1.0,scale,0.10,0.197914,0.211205,2.756898,0.107310,40
5,15,1.0,scale,0.05,0.197229,0.206639,2.757238,0.106983,40
6,20,10.0,scale,0.50,0.193798,0.205604,2.830114,0.104995,40
7,20,10.0,scale,0.10,0.192012,0.199460,2.841720,0.105880,40
8,20,10.0,scale,0.05,0.191973,0.198859,2.842826,0.105801,40
9,20,0.1,scale,0.05,0.187815,0.188343,2.785527,0.113726,40
10,20,0.1,scale,0.10,0.187505,0.186992,2.785712,0.113597,40
11,10,1.0,scale,0.50,0.185089,0.206470,2.766519,0.109964,40
12,15,10.0,scale,0.50,0.184688,0.193387,2.830157,0.107717,40
13,10,1.0,scale,0.10,0.181418,0.205653,2.767804,0.109567,40
14,10,1.0,scale,0.05,0.180731,0.206170,2.767886,0.109851,40
15,15,10.0,scale,0.10,0.180082,0.190568,2.845830,0.110651,40
16,15,10.0,scale,0.05,0.179815,0.190724,2.847249,0.111067,40
17,15,0.1,scale,0.05,0.178239,0.194001,2.785843,0.114484,40
18,15,0.1,scale,0.10,0.177618,0.193073,2.786290,0.114413,40
19,20,0.1,scale,0.50,0.175921,0.180375,2.791427,0.112619,40

====================================================================================================
BEST SETTINGS
====================================================================================================
PC count: 20
C: 1.0
gamma: scale
epsilon: 0.1

Mean validation Spearman: 0.2102
Median validation Spearman: 0.2059
Mean validation MAE: 2.7475
Rounded validation accuracy: 0.1083

Saved tuning summary:
/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/svr_pca_tuning_summary.csv

Saved subject-level tuning results:
/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/svr_pca_tuning_subject_results.csv

In [ ]:
# ============================================================
# EXPERIMENT 2 — SVR POLYNOMIAL KERNEL, DEGREE 3
# Keep everything else the same as Entry 1
# ============================================================

from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error
from scipy.stats import spearmanr
import numpy as np
import pandas as pd


results = []


for subject in subjects:

    d = subject_data[subject]

    # Same 20 PCs as Entry 1
    X_train = d["X_train"][:, :20]
    y_train = d["y_train"]

    X_validation = d["X_validation"][:, :20]
    y_validation = d["y_validation"]


    # --------------------------------------------------------
    # POLYNOMIAL SVR
    # --------------------------------------------------------

    model = SVR(
        kernel="poly",
        degree=3,
        C=1.0,
        gamma="scale",
        epsilon=0.1,
    )

    model.fit(
        X_train,
        y_train
    )


    # ========================================================
    # TRAINING RESULTS
    # ========================================================

    train_pred = model.predict(
        X_train
    )

    train_rounded = np.clip(
        np.rint(train_pred),
        1,
        13
    ).astype(int)

    train_accuracy = np.mean(
        train_rounded == y_train.astype(int)
    )

    train_mae = mean_absolute_error(
        y_train,
        train_pred
    )

    train_spearman = spearmanr(
        y_train,
        train_pred
    ).statistic


    # ========================================================
    # VALIDATION RESULTS
    # ========================================================

    val_pred = model.predict(
        X_validation
    )

    val_rounded = np.clip(
        np.rint(val_pred),
        1,
        13
    ).astype(int)

    val_accuracy = np.mean(
        val_rounded == y_validation.astype(int)
    )

    val_mae = mean_absolute_error(
        y_validation,
        val_pred
    )

    val_spearman = spearmanr(
        y_validation,
        val_pred
    ).statistic


    results.append({
        "subject_id": subject,

        "train_accuracy": train_accuracy,
        "train_mae": train_mae,
        "train_spearman": train_spearman,

        "validation_accuracy": val_accuracy,
        "validation_mae": val_mae,
        "validation_spearman": val_spearman,
    })


# ============================================================
# RESULTS
# ============================================================

poly_results = pd.DataFrame(results)


summary = pd.DataFrame({
    "accuracy": [
        poly_results["train_accuracy"].mean(),
        poly_results["validation_accuracy"].mean(),
    ],

    "mae": [
        poly_results["train_mae"].mean(),
        poly_results["validation_mae"].mean(),
    ],

    "spearman": [
        poly_results["train_spearman"].mean(),
        poly_results["validation_spearman"].mean(),
    ],
}, index=[
    "Training samples on training subjects",
    "Validation samples on training subjects",
])


print("=" * 80)
print("SVR — POLYNOMIAL KERNEL DEGREE 3")
print("=" * 80)

display(
    summary.round(4)
)


print("\nSUBJECT-BY-SUBJECT RESULTS")

display(
    poly_results.round(4)
)


# ============================================================
# SAVE
# ============================================================

save_path = (
    RESULTS_FOLDER /
    "svr_poly_degree3_results.csv"
)

poly_results.to_csv(
    save_path,
    index=False
)

print("\nSaved to:")
print(save_path)

================================================================================
SVR — POLYNOMIAL KERNEL DEGREE 3
================================================================================

                                         accuracy      mae  spearman
Training samples on training subjects      0.2249   2.3751    0.4845
Validation samples on training subjects    0.1094  31.2545    0.1428

SUBJECT-BY-SUBJECT RESULTS

,subject_id,train_accuracy,train_mae,train_spearman,validation_accuracy,validation_mae,validation_spearman
0,34,0.2824,2.1128,0.5981,0.1393,2.7467,0.2201
1,35,0.2251,2.3505,0.5917,0.1144,2.7779,0.2261
2,36,0.2405,2.3026,0.4455,0.0894,3.2106,0.0747
3,38,0.1766,2.5166,0.4151,0.0919,8.6082,0.1113
4,42,0.2065,2.4863,0.3194,0.1067,3.1178,0.0521
5,43,0.1868,2.4835,0.4830,0.1188,3.4643,0.1385
6,44,0.2156,2.3648,0.5351,0.0879,2.9200,0.1908
7,45,0.2988,2.1938,0.5913,0.0873,2.8381,0.1292
8,48,0.2599,2.1990,0.6100,0.1117,966.5524,0.1146
9,51,0.2552,2.2129,0.6540,0.0921,3.1358,0.2536
10,52,0.2914,2.1644,0.5860,0.1114,2.8321,0.0990
11,53,0.1541,2.6794,0.2439,0.0976,16.6777,0.1029
12,54,0.2632,2.2038,0.5716,0.1070,3.1569,0.3169
13,55,0.1925,2.5136,0.3928,0.1165,3.1378,0.0515
14,56,0.1882,2.5189,0.3530,0.1199,2.9505,0.0917
15,58,0.2365,2.3665,0.5261,0.1313,2.9031,0.1437
16,59,0.2427,2.3358,0.4705,0.1154,3.0014,0.0155
17,62,0.2497,2.2259,0.6050,0.0934,2.8902,0.0848
18,65,0.2262,2.3729,0.4763,0.0865,3.3947,0.2383
19,67,0.1957,2.5233,0.3965,0.0854,4.2485,0.0261
20,68,0.2514,2.2682,0.5596,0.0914,3.0723,0.2334
21,69,0.2081,2.4068,0.4933,0.1132,106.2024,0.1792
22,70,0.2036,2.5224,0.4347,0.1201,3.1894,0.1427
23,73,0.2071,2.4261,0.4666,0.1194,3.0645,0.0516
24,74,0.2190,2.3807,0.4465,0.1176,3.2826,0.0677
25,76,0.2436,2.2836,0.4775,0.1320,3.0121,0.1336
26,77,0.2253,2.3754,0.4453,0.0849,14.3370,0.1141
27,79,0.2112,2.4532,0.4303,0.1189,3.2246,0.2246
28,80,0.2756,2.1938,0.5120,0.0986,2.8055,0.1370
29,81,0.2148,2.3933,0.5198,0.0932,2.8021,0.1690
30,83,0.2099,2.4318,0.4204,0.1102,21.5596,0.0664
31,85,0.2649,2.2806,0.5129,0.1000,2.8545,0.1929
32,87,0.2411,2.3207,0.4733,0.1163,4.3212,0.0857
33,88,0.2190,2.4192,0.4973,0.1284,8.5342,0.2389
34,90,0.2121,2.4697,0.5060,0.1243,6.8151,0.1418
35,91,0.1969,2.5316,0.4144,0.1008,3.2854,0.1763
36,93,0.1701,2.5259,0.4017,0.1247,4.0952,0.1359
37,95,0.2111,2.4363,0.4903,0.1205,2.8048,0.1862
38,96,0.1900,2.3932,0.4948,0.1175,3.0876,0.2564
39,97,0.2316,2.3654,0.5165,0.1397,3.2664,0.0963

Saved to:
/content/drive/MyDrive/EEG Shared/Results/Luke/3D_Models_From_Clean_PCA/svr_poly_degree3_results.csv