# EEG 3B — Exact 40 Development / 25 Holdout Subjects

Exactly 65 subjects. Whole 24-row `epoch_uid` blocks only.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path
import pandas as pd

BASE = Path(
    "/content/drive/MyDrive/EEG Shared/Processed_data/"
    "Kosachenko_All_Subjects/3B_Exact_40_25_Split"
)

files = {
    "DEVELOPMENT — TRAIN":
        BASE / "subject_train/train.csv",

    "DEVELOPMENT — VALIDATION":
        BASE / "subject_train/validation.csv",

    "DEVELOPMENT — HOLDOUT":
        BASE / "subject_train/holdout.csv",

    "FINAL SUBJECTS — TRAIN":
        BASE / "subject_holdout/train.csv",

    "FINAL SUBJECTS — VALIDATION":
        BASE / "subject_holdout/validation.csv",

    "FINAL SUBJECTS — HOLDOUT":
        BASE / "subject_holdout/holdout.csv",
}

for name, path in files.items():

    print("\n")
    print("=" * 100)
    print(name)
    print("=" * 100)

    if not path.exists():
        print("MISSING:", path)
        continue

    size_gb = path.stat().st_size / (1024 ** 3)

    # Only reads first 5 rows — NOT whole CSV
    preview = pd.read_csv(
        path,
        nrows=5,
        low_memory=False
    )

    print(f"Size: {size_gb:.3f} GB")
    print(f"Columns: {len(preview.columns)}")
    print("\nColumn names:")
    print(preview.columns.tolist())

    print("\nFirst 5 rows:")
    display(preview)

====================================================================================================
DEVELOPMENT — TRAIN
====================================================================================================
Size: 1.683 GB
Columns: 112

Column names:
['dataset', 'subject_id', 'recording_id', 'label', 'condition', 'source_file', 'absolute_load', 'load_in_sequence', 'epoch_id', 'epoch_uid', 'row_in_epoch', 'time_seconds', 'epoch_start_seconds', 'event_count', 'event_labels', 'Fp1_Delta', 'Fp2_Delta', 'F7_Delta', 'F3_Delta', 'Fz_Delta', 'F4_Delta', 'F8_Delta', 'T7_Delta', 'C3_Delta', 'Cz_Delta', 'C4_Delta', 'T8_Delta', 'P7_Delta', 'P3_Delta', 'Pz_Delta', 'P4_Delta', 'P8_Delta', 'O1_Delta', 'O2_Delta', 'Fp1_Theta', 'Fp2_Theta', 'F7_Theta', 'F3_Theta', 'Fz_Theta', 'F4_Theta', 'F8_Theta', 'T7_Theta', 'C3_Theta', 'Cz_Theta', 'C4_Theta', 'T8_Theta', 'P7_Theta', 'P3_Theta', 'Pz_Theta', 'P4_Theta', 'P8_Theta', 'O1_Theta', 'O2_Theta', 'Fp1_Alpha', 'Fp2_Alpha', 'F7_Alpha', 'F3_Alpha', 'Fz_Alpha', 'F4_Alpha', 'F8_Alpha', 'T7_Alpha', 'C3_Alpha', 'Cz_Alpha', 'C4_Alpha', 'T8_Alpha', 'P7_Alpha', 'P3_Alpha', 'Pz_Alpha', 'P4_Alpha', 'P8_Alpha', 'O1_Alpha', 'O2_Alpha', 'Fp1_Beta', 'Fp2_Beta', 'F7_Beta', 'F3_Beta', 'Fz_Beta', 'F4_Beta', 'F8_Beta', 'T7_Beta', 'C3_Beta', 'Cz_Beta', 'C4_Beta', 'T8_Beta', 'P7_Beta', 'P3_Beta', 'Pz_Beta', 'P4_Beta', 'P8_Beta', 'O1_Beta', 'O2_Beta', 'Fp1_Gamma', 'Fp2_Gamma', 'F7_Gamma', 'F3_Gamma', 'Fz_Gamma', 'F4_Gamma', 'F8_Gamma', 'T7_Gamma', 'C3_Gamma', 'Cz_Gamma', 'C4_Gamma', 'T8_Gamma', 'P7_Gamma', 'P3_Gamma', 'Pz_Gamma', 'P4_Gamma', 'P8_Gamma', 'O1_Gamma', 'O2_Gamma', 'subject_split', 'sample_split']

First 5 rows:

,dataset,subject_id,recording_id,label,condition,source_file,absolute_load,load_in_sequence,epoch_id,epoch_uid,...,T8_Gamma,P7_Gamma,P3_Gamma,Pz_Gamma,P4_Gamma,P8_Gamma,O1_Gamma,O2_Gamma,subject_split,sample_split
0,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,3.0,2,051__sub-051_task-memory_eeg__digit_epoch_2,...,6.200436e-11,2.756172e-11,1.417743e-11,1.133028e-11,8.370455e-12,7.891637e-12,3.021025e-11,2.239644e-11,subject_train,train
1,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,3.0,2,051__sub-051_task-memory_eeg__digit_epoch_2,...,7.264501e-11,2.203735e-11,2.012404e-11,1.680764e-11,1.327806e-11,1.838677e-11,3.409768e-11,2.062581e-11,subject_train,train
2,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,3.0,2,051__sub-051_task-memory_eeg__digit_epoch_2,...,4.263042e-11,3.772589e-11,1.814945e-11,1.152190e-11,1.330768e-11,3.667725e-11,2.981390e-11,2.496506e-11,subject_train,train
3,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,3.0,2,051__sub-051_task-memory_eeg__digit_epoch_2,...,7.798203e-11,5.565596e-11,2.505360e-11,1.619674e-11,1.128186e-11,2.377802e-11,2.387982e-11,2.004232e-11,subject_train,train
4,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,3.0,2,051__sub-051_task-memory_eeg__digit_epoch_2,...,3.690513e-11,7.588208e-11,1.528718e-11,1.337237e-11,1.409511e-11,4.933638e-11,1.902663e-11,1.756996e-11,subject_train,train

====================================================================================================
DEVELOPMENT — VALIDATION
====================================================================================================
Size: 0.843 GB
Columns: 112

Column names:
['dataset', 'subject_id', 'recording_id', 'label', 'condition', 'source_file', 'absolute_load', 'load_in_sequence', 'epoch_id', 'epoch_uid', 'row_in_epoch', 'time_seconds', 'epoch_start_seconds', 'event_count', 'event_labels', 'Fp1_Delta', 'Fp2_Delta', 'F7_Delta', 'F3_Delta', 'Fz_Delta', 'F4_Delta', 'F8_Delta', 'T7_Delta', 'C3_Delta', 'Cz_Delta', 'C4_Delta', 'T8_Delta', 'P7_Delta', 'P3_Delta', 'Pz_Delta', 'P4_Delta', 'P8_Delta', 'O1_Delta', 'O2_Delta', 'Fp1_Theta', 'Fp2_Theta', 'F7_Theta', 'F3_Theta', 'Fz_Theta', 'F4_Theta', 'F8_Theta', 'T7_Theta', 'C3_Theta', 'Cz_Theta', 'C4_Theta', 'T8_Theta', 'P7_Theta', 'P3_Theta', 'Pz_Theta', 'P4_Theta', 'P8_Theta', 'O1_Theta', 'O2_Theta', 'Fp1_Alpha', 'Fp2_Alpha', 'F7_Alpha', 'F3_Alpha', 'Fz_Alpha', 'F4_Alpha', 'F8_Alpha', 'T7_Alpha', 'C3_Alpha', 'Cz_Alpha', 'C4_Alpha', 'T8_Alpha', 'P7_Alpha', 'P3_Alpha', 'Pz_Alpha', 'P4_Alpha', 'P8_Alpha', 'O1_Alpha', 'O2_Alpha', 'Fp1_Beta', 'Fp2_Beta', 'F7_Beta', 'F3_Beta', 'Fz_Beta', 'F4_Beta', 'F8_Beta', 'T7_Beta', 'C3_Beta', 'Cz_Beta', 'C4_Beta', 'T8_Beta', 'P7_Beta', 'P3_Beta', 'Pz_Beta', 'P4_Beta', 'P8_Beta', 'O1_Beta', 'O2_Beta', 'Fp1_Gamma', 'Fp2_Gamma', 'F7_Gamma', 'F3_Gamma', 'Fz_Gamma', 'F4_Gamma', 'F8_Gamma', 'T7_Gamma', 'C3_Gamma', 'Cz_Gamma', 'C4_Gamma', 'T8_Gamma', 'P7_Gamma', 'P3_Gamma', 'Pz_Gamma', 'P4_Gamma', 'P8_Gamma', 'O1_Gamma', 'O2_Gamma', 'subject_split', 'sample_split']

First 5 rows:

,dataset,subject_id,recording_id,label,condition,source_file,absolute_load,load_in_sequence,epoch_id,epoch_uid,...,T8_Gamma,P7_Gamma,P3_Gamma,Pz_Gamma,P4_Gamma,P8_Gamma,O1_Gamma,O2_Gamma,subject_split,sample_split
0,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,9.0,1.0,5,051__sub-051_task-memory_eeg__digit_epoch_5,...,3.502479e-11,1.479835e-11,6.861190e-12,1.040720e-11,8.341063e-12,2.641571e-11,1.958046e-11,1.786912e-11,subject_train,validation
1,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,9.0,1.0,5,051__sub-051_task-memory_eeg__digit_epoch_5,...,1.362933e-11,5.993671e-11,1.412818e-11,1.016049e-11,1.240747e-11,5.140509e-11,1.312408e-11,8.637047e-12,subject_train,validation
2,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,9.0,1.0,5,051__sub-051_task-memory_eeg__digit_epoch_5,...,9.807705e-12,5.052419e-11,1.243634e-11,8.334565e-12,1.726712e-11,8.893113e-11,9.811058e-12,8.107896e-12,subject_train,validation
3,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,9.0,1.0,5,051__sub-051_task-memory_eeg__digit_epoch_5,...,8.693089e-11,1.111590e-10,8.986532e-12,2.084045e-12,2.197110e-12,3.215889e-11,1.289965e-11,8.573681e-12,subject_train,validation
4,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,9.0,1.0,5,051__sub-051_task-memory_eeg__digit_epoch_5,...,3.309552e-11,6.684748e-11,1.808995e-11,1.753372e-11,1.275750e-11,3.283772e-11,2.221219e-11,2.334940e-11,subject_train,validation

====================================================================================================
DEVELOPMENT — HOLDOUT
====================================================================================================
Size: 0.843 GB
Columns: 112

Column names:
['dataset', 'subject_id', 'recording_id', 'label', 'condition', 'source_file', 'absolute_load', 'load_in_sequence', 'epoch_id', 'epoch_uid', 'row_in_epoch', 'time_seconds', 'epoch_start_seconds', 'event_count', 'event_labels', 'Fp1_Delta', 'Fp2_Delta', 'F7_Delta', 'F3_Delta', 'Fz_Delta', 'F4_Delta', 'F8_Delta', 'T7_Delta', 'C3_Delta', 'Cz_Delta', 'C4_Delta', 'T8_Delta', 'P7_Delta', 'P3_Delta', 'Pz_Delta', 'P4_Delta', 'P8_Delta', 'O1_Delta', 'O2_Delta', 'Fp1_Theta', 'Fp2_Theta', 'F7_Theta', 'F3_Theta', 'Fz_Theta', 'F4_Theta', 'F8_Theta', 'T7_Theta', 'C3_Theta', 'Cz_Theta', 'C4_Theta', 'T8_Theta', 'P7_Theta', 'P3_Theta', 'Pz_Theta', 'P4_Theta', 'P8_Theta', 'O1_Theta', 'O2_Theta', 'Fp1_Alpha', 'Fp2_Alpha', 'F7_Alpha', 'F3_Alpha', 'Fz_Alpha', 'F4_Alpha', 'F8_Alpha', 'T7_Alpha', 'C3_Alpha', 'Cz_Alpha', 'C4_Alpha', 'T8_Alpha', 'P7_Alpha', 'P3_Alpha', 'Pz_Alpha', 'P4_Alpha', 'P8_Alpha', 'O1_Alpha', 'O2_Alpha', 'Fp1_Beta', 'Fp2_Beta', 'F7_Beta', 'F3_Beta', 'Fz_Beta', 'F4_Beta', 'F8_Beta', 'T7_Beta', 'C3_Beta', 'Cz_Beta', 'C4_Beta', 'T8_Beta', 'P7_Beta', 'P3_Beta', 'Pz_Beta', 'P4_Beta', 'P8_Beta', 'O1_Beta', 'O2_Beta', 'Fp1_Gamma', 'Fp2_Gamma', 'F7_Gamma', 'F3_Gamma', 'Fz_Gamma', 'F4_Gamma', 'F8_Gamma', 'T7_Gamma', 'C3_Gamma', 'Cz_Gamma', 'C4_Gamma', 'T8_Gamma', 'P7_Gamma', 'P3_Gamma', 'Pz_Gamma', 'P4_Gamma', 'P8_Gamma', 'O1_Gamma', 'O2_Gamma', 'subject_split', 'sample_split']

First 5 rows:

,dataset,subject_id,recording_id,label,condition,source_file,absolute_load,load_in_sequence,epoch_id,epoch_uid,...,T8_Gamma,P7_Gamma,P3_Gamma,Pz_Gamma,P4_Gamma,P8_Gamma,O1_Gamma,O2_Gamma,subject_split,sample_split
0,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,1.0,0,051__sub-051_task-memory_eeg__digit_epoch_0,...,3.922823e-11,4.020498e-11,1.370141e-11,9.854557e-12,5.976247e-12,2.781327e-11,1.407252e-11,8.503737e-12,subject_train,holdout
1,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,1.0,0,051__sub-051_task-memory_eeg__digit_epoch_0,...,4.098087e-11,1.137856e-10,1.202967e-11,9.675122e-12,1.114566e-11,9.219678e-11,2.027284e-11,1.710998e-11,subject_train,holdout
2,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,1.0,0,051__sub-051_task-memory_eeg__digit_epoch_0,...,1.189166e-10,8.802357e-11,1.595447e-11,8.500645e-12,1.530579e-11,9.322350e-11,1.222844e-11,9.300581e-12,subject_train,holdout
3,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,1.0,0,051__sub-051_task-memory_eeg__digit_epoch_0,...,4.075142e-11,6.834592e-11,1.297144e-11,1.070597e-11,1.588149e-11,2.448913e-11,2.052411e-11,2.943276e-11,subject_train,holdout
4,Kosachenko,51,sub-051_task-memory_eeg,memory,control,sub-051_task-memory_eeg.set,5.0,1.0,0,051__sub-051_task-memory_eeg__digit_epoch_0,...,2.614751e-11,2.523614e-11,1.171059e-11,1.329653e-11,1.464121e-11,5.426856e-11,3.059185e-11,2.344153e-11,subject_train,holdout

====================================================================================================
FINAL SUBJECTS — TRAIN
====================================================================================================
Size: 0.841 GB
Columns: 112

Column names:
['dataset', 'subject_id', 'recording_id', 'label', 'condition', 'source_file', 'absolute_load', 'load_in_sequence', 'epoch_id', 'epoch_uid', 'row_in_epoch', 'time_seconds', 'epoch_start_seconds', 'event_count', 'event_labels', 'Fp1_Delta', 'Fp2_Delta', 'F7_Delta', 'F3_Delta', 'Fz_Delta', 'F4_Delta', 'F8_Delta', 'T7_Delta', 'C3_Delta', 'Cz_Delta', 'C4_Delta', 'T8_Delta', 'P7_Delta', 'P3_Delta', 'Pz_Delta', 'P4_Delta', 'P8_Delta', 'O1_Delta', 'O2_Delta', 'Fp1_Theta', 'Fp2_Theta', 'F7_Theta', 'F3_Theta', 'Fz_Theta', 'F4_Theta', 'F8_Theta', 'T7_Theta', 'C3_Theta', 'Cz_Theta', 'C4_Theta', 'T8_Theta', 'P7_Theta', 'P3_Theta', 'Pz_Theta', 'P4_Theta', 'P8_Theta', 'O1_Theta', 'O2_Theta', 'Fp1_Alpha', 'Fp2_Alpha', 'F7_Alpha', 'F3_Alpha', 'Fz_Alpha', 'F4_Alpha', 'F8_Alpha', 'T7_Alpha', 'C3_Alpha', 'Cz_Alpha', 'C4_Alpha', 'T8_Alpha', 'P7_Alpha', 'P3_Alpha', 'Pz_Alpha', 'P4_Alpha', 'P8_Alpha', 'O1_Alpha', 'O2_Alpha', 'Fp1_Beta', 'Fp2_Beta', 'F7_Beta', 'F3_Beta', 'Fz_Beta', 'F4_Beta', 'F8_Beta', 'T7_Beta', 'C3_Beta', 'Cz_Beta', 'C4_Beta', 'T8_Beta', 'P7_Beta', 'P3_Beta', 'Pz_Beta', 'P4_Beta', 'P8_Beta', 'O1_Beta', 'O2_Beta', 'Fp1_Gamma', 'Fp2_Gamma', 'F7_Gamma', 'F3_Gamma', 'Fz_Gamma', 'F4_Gamma', 'F8_Gamma', 'T7_Gamma', 'C3_Gamma', 'Cz_Gamma', 'C4_Gamma', 'T8_Gamma', 'P7_Gamma', 'P3_Gamma', 'Pz_Gamma', 'P4_Gamma', 'P8_Gamma', 'O1_Gamma', 'O2_Gamma', 'subject_split', 'sample_split']

First 5 rows:

,dataset,subject_id,recording_id,label,condition,source_file,absolute_load,load_in_sequence,epoch_id,epoch_uid,...,T8_Gamma,P7_Gamma,P3_Gamma,Pz_Gamma,P4_Gamma,P8_Gamma,O1_Gamma,O2_Gamma,subject_split,sample_split
0,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,1.0,0,086__sub-086_task-memory_eeg__digit_epoch_0,...,1.829694e-10,1.559045e-10,1.034488e-11,6.201177e-12,1.686895e-11,5.225874e-11,7.356448e-12,1.186029e-11,subject_holdout,train
1,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,1.0,0,086__sub-086_task-memory_eeg__digit_epoch_0,...,2.712805e-10,3.688490e-10,1.711667e-11,1.411172e-11,3.652570e-11,2.174676e-10,2.389890e-11,3.121319e-11,subject_holdout,train
2,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,1.0,0,086__sub-086_task-memory_eeg__digit_epoch_0,...,3.776650e-10,3.076371e-10,2.501175e-11,1.692440e-11,2.483497e-11,1.501610e-10,3.187480e-11,4.225328e-11,subject_holdout,train
3,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,1.0,0,086__sub-086_task-memory_eeg__digit_epoch_0,...,9.721197e-11,2.710061e-10,1.991854e-11,6.425205e-12,1.621622e-11,1.489880e-10,1.139368e-11,1.493706e-11,subject_holdout,train
4,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,1.0,0,086__sub-086_task-memory_eeg__digit_epoch_0,...,6.289664e-10,1.708998e-10,1.729297e-11,1.353259e-11,3.668117e-11,1.645249e-10,2.445569e-11,2.886130e-11,subject_holdout,train

====================================================================================================
FINAL SUBJECTS — VALIDATION
====================================================================================================
Size: 0.482 GB
Columns: 112

Column names:
['dataset', 'subject_id', 'recording_id', 'label', 'condition', 'source_file', 'absolute_load', 'load_in_sequence', 'epoch_id', 'epoch_uid', 'row_in_epoch', 'time_seconds', 'epoch_start_seconds', 'event_count', 'event_labels', 'Fp1_Delta', 'Fp2_Delta', 'F7_Delta', 'F3_Delta', 'Fz_Delta', 'F4_Delta', 'F8_Delta', 'T7_Delta', 'C3_Delta', 'Cz_Delta', 'C4_Delta', 'T8_Delta', 'P7_Delta', 'P3_Delta', 'Pz_Delta', 'P4_Delta', 'P8_Delta', 'O1_Delta', 'O2_Delta', 'Fp1_Theta', 'Fp2_Theta', 'F7_Theta', 'F3_Theta', 'Fz_Theta', 'F4_Theta', 'F8_Theta', 'T7_Theta', 'C3_Theta', 'Cz_Theta', 'C4_Theta', 'T8_Theta', 'P7_Theta', 'P3_Theta', 'Pz_Theta', 'P4_Theta', 'P8_Theta', 'O1_Theta', 'O2_Theta', 'Fp1_Alpha', 'Fp2_Alpha', 'F7_Alpha', 'F3_Alpha', 'Fz_Alpha', 'F4_Alpha', 'F8_Alpha', 'T7_Alpha', 'C3_Alpha', 'Cz_Alpha', 'C4_Alpha', 'T8_Alpha', 'P7_Alpha', 'P3_Alpha', 'Pz_Alpha', 'P4_Alpha', 'P8_Alpha', 'O1_Alpha', 'O2_Alpha', 'Fp1_Beta', 'Fp2_Beta', 'F7_Beta', 'F3_Beta', 'Fz_Beta', 'F4_Beta', 'F8_Beta', 'T7_Beta', 'C3_Beta', 'Cz_Beta', 'C4_Beta', 'T8_Beta', 'P7_Beta', 'P3_Beta', 'Pz_Beta', 'P4_Beta', 'P8_Beta', 'O1_Beta', 'O2_Beta', 'Fp1_Gamma', 'Fp2_Gamma', 'F7_Gamma', 'F3_Gamma', 'Fz_Gamma', 'F4_Gamma', 'F8_Gamma', 'T7_Gamma', 'C3_Gamma', 'Cz_Gamma', 'C4_Gamma', 'T8_Gamma', 'P7_Gamma', 'P3_Gamma', 'Pz_Gamma', 'P4_Gamma', 'P8_Gamma', 'O1_Gamma', 'O2_Gamma', 'subject_split', 'sample_split']

First 5 rows:

,dataset,subject_id,recording_id,label,condition,source_file,absolute_load,load_in_sequence,epoch_id,epoch_uid,...,T8_Gamma,P7_Gamma,P3_Gamma,Pz_Gamma,P4_Gamma,P8_Gamma,O1_Gamma,O2_Gamma,subject_split,sample_split
0,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,5.0,4,086__sub-086_task-memory_eeg__digit_epoch_4,...,3.240968e-10,1.932244e-10,9.956080e-12,7.433518e-12,2.137890e-11,1.324716e-10,1.107751e-11,1.529597e-11,subject_holdout,validation
1,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,5.0,4,086__sub-086_task-memory_eeg__digit_epoch_4,...,4.221355e-10,3.199794e-10,2.976007e-11,1.534218e-11,3.028818e-11,1.221274e-10,1.365908e-11,1.984512e-11,subject_holdout,validation
2,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,5.0,4,086__sub-086_task-memory_eeg__digit_epoch_4,...,2.779723e-10,2.098318e-10,2.424055e-11,7.804538e-12,2.121715e-11,1.249335e-10,1.205565e-11,1.567549e-11,subject_holdout,validation
3,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,5.0,4,086__sub-086_task-memory_eeg__digit_epoch_4,...,6.973921e-11,1.388282e-10,1.595553e-11,6.150776e-12,1.239111e-11,8.237096e-11,7.141516e-12,7.660078e-12,subject_holdout,validation
4,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,5.0,4,086__sub-086_task-memory_eeg__digit_epoch_4,...,2.562160e-10,9.245523e-11,8.729139e-12,9.593152e-12,1.162396e-11,7.329869e-11,1.005143e-11,2.053224e-11,subject_holdout,validation

====================================================================================================
FINAL SUBJECTS — HOLDOUT
====================================================================================================
Size: 0.460 GB
Columns: 112

Column names:
['dataset', 'subject_id', 'recording_id', 'label', 'condition', 'source_file', 'absolute_load', 'load_in_sequence', 'epoch_id', 'epoch_uid', 'row_in_epoch', 'time_seconds', 'epoch_start_seconds', 'event_count', 'event_labels', 'Fp1_Delta', 'Fp2_Delta', 'F7_Delta', 'F3_Delta', 'Fz_Delta', 'F4_Delta', 'F8_Delta', 'T7_Delta', 'C3_Delta', 'Cz_Delta', 'C4_Delta', 'T8_Delta', 'P7_Delta', 'P3_Delta', 'Pz_Delta', 'P4_Delta', 'P8_Delta', 'O1_Delta', 'O2_Delta', 'Fp1_Theta', 'Fp2_Theta', 'F7_Theta', 'F3_Theta', 'Fz_Theta', 'F4_Theta', 'F8_Theta', 'T7_Theta', 'C3_Theta', 'Cz_Theta', 'C4_Theta', 'T8_Theta', 'P7_Theta', 'P3_Theta', 'Pz_Theta', 'P4_Theta', 'P8_Theta', 'O1_Theta', 'O2_Theta', 'Fp1_Alpha', 'Fp2_Alpha', 'F7_Alpha', 'F3_Alpha', 'Fz_Alpha', 'F4_Alpha', 'F8_Alpha', 'T7_Alpha', 'C3_Alpha', 'Cz_Alpha', 'C4_Alpha', 'T8_Alpha', 'P7_Alpha', 'P3_Alpha', 'Pz_Alpha', 'P4_Alpha', 'P8_Alpha', 'O1_Alpha', 'O2_Alpha', 'Fp1_Beta', 'Fp2_Beta', 'F7_Beta', 'F3_Beta', 'Fz_Beta', 'F4_Beta', 'F8_Beta', 'T7_Beta', 'C3_Beta', 'Cz_Beta', 'C4_Beta', 'T8_Beta', 'P7_Beta', 'P3_Beta', 'Pz_Beta', 'P4_Beta', 'P8_Beta', 'O1_Beta', 'O2_Beta', 'Fp1_Gamma', 'Fp2_Gamma', 'F7_Gamma', 'F3_Gamma', 'Fz_Gamma', 'F4_Gamma', 'F8_Gamma', 'T7_Gamma', 'C3_Gamma', 'Cz_Gamma', 'C4_Gamma', 'T8_Gamma', 'P7_Gamma', 'P3_Gamma', 'Pz_Gamma', 'P4_Gamma', 'P8_Gamma', 'O1_Gamma', 'O2_Gamma', 'subject_split', 'sample_split']

First 5 rows:

,dataset,subject_id,recording_id,label,condition,source_file,absolute_load,load_in_sequence,epoch_id,epoch_uid,...,T8_Gamma,P7_Gamma,P3_Gamma,Pz_Gamma,P4_Gamma,P8_Gamma,O1_Gamma,O2_Gamma,subject_split,sample_split
0,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,3.0,2,086__sub-086_task-memory_eeg__digit_epoch_2,...,4.615011e-10,5.229109e-10,2.957168e-11,7.760321e-12,5.552594e-11,4.723600e-10,1.502763e-11,1.505982e-11,subject_holdout,holdout
1,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,3.0,2,086__sub-086_task-memory_eeg__digit_epoch_2,...,1.009067e-10,2.865478e-10,4.648011e-11,1.685861e-11,1.110206e-11,9.007022e-11,3.162517e-11,3.910101e-11,subject_holdout,holdout
2,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,3.0,2,086__sub-086_task-memory_eeg__digit_epoch_2,...,5.177992e-10,1.455889e-10,1.079410e-11,5.448508e-12,2.366333e-11,1.083961e-10,1.064071e-11,1.685412e-11,subject_holdout,holdout
3,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,3.0,2,086__sub-086_task-memory_eeg__digit_epoch_2,...,3.546374e-10,2.870857e-10,2.629438e-11,1.493109e-11,6.457034e-11,4.408649e-10,2.099269e-11,2.035878e-11,subject_holdout,holdout
4,Kosachenko,86,sub-086_task-memory_eeg,memory,control,sub-086_task-memory_eeg.set,5.0,3.0,2,086__sub-086_task-memory_eeg__digit_epoch_2,...,3.178801e-10,3.060635e-10,8.847159e-12,1.224406e-11,3.532282e-11,2.761660e-10,4.234155e-11,4.610108e-11,subject_holdout,holdout

In [ ]:
from pathlib import Path
import pandas as pd
import sys
import importlib
import shutil
import os
import time

# ============================================================
# PATHS
# ============================================================

CODE_DIR = Path(
    "/content/drive/MyDrive/EEG Shared/Code/Code Luke"
)

SOURCE_DIR = Path(
    "/content/drive/MyDrive/EEG Shared/Processed_data/"
    "Kosachenko_All_Subjects"
)

OUTPUT_DIR = SOURCE_DIR / "3B_Exact_40_25_Split"

MANIFEST_PATH = OUTPUT_DIR / "subject_assignments.csv"

DRIVE_DIR = OUTPUT_DIR / "subject_holdout"

DRIVE_TRAIN = DRIVE_DIR / "train.csv"
DRIVE_VALIDATION = DRIVE_DIR / "validation.csv"
DRIVE_HOLDOUT = DRIVE_DIR / "holdout.csv"

LOCAL_DIR = Path("/content/3b_holdout_full_rebuild")
LOCAL_DIR.mkdir(parents=True, exist_ok=True)

LOCAL_TRAIN = LOCAL_DIR / "train.csv"
LOCAL_VALIDATION = LOCAL_DIR / "validation.csv"
LOCAL_HOLDOUT = LOCAL_DIR / "holdout.csv"


# ============================================================
# IMPORT ORIGINAL 3B HELPERS
# ============================================================

if str(CODE_DIR) not in sys.path:
    sys.path.insert(0, str(CODE_DIR))

module_name = "load_data_3b_exact_40_25_split_50_25_25"

m = importlib.import_module(module_name)
m = importlib.reload(m)

_read_csv_with_retries = m._read_csv_with_retries
_subject_from_filename = m._subject_from_filename
_normalize_source_frame = m._normalize_source_frame
_split_epoch_ids = m._split_epoch_ids
_append_frame = m._append_frame
find_processed_csvs = m.find_processed_csvs

print("3B functions loaded.")


# ============================================================
# SETTINGS
# ============================================================

RANDOM_STATE = 1

FRACTIONS = {
    "train": 0.50,
    "validation": 0.25,
    "holdout": 0.25,
}


def norm_subject(x):
    s = str(x).strip()

    if s.endswith(".0"):
        s = s[:-2]

    if s.isdigit():
        return str(int(s))

    return s


# ============================================================
# DELETE OLD LOCAL TEMP FILES
# ============================================================

for p in [
    LOCAL_TRAIN,
    LOCAL_VALIDATION,
    LOCAL_HOLDOUT,
]:
    if p.exists():
        p.unlink()


# ============================================================
# GET EXACT ORIGINAL 25 HOLDOUT SUBJECTS
# ============================================================

manifest = pd.read_csv(MANIFEST_PATH)

holdout_subjects = [
    norm_subject(x)
    for x in manifest.loc[
        manifest["subject_split"] == "subject_holdout",
        "subject_id"
    ].tolist()
]

print("Holdout subjects:", len(holdout_subjects))
print([x.zfill(3) for x in holdout_subjects])

if len(holdout_subjects) != 25:
    raise RuntimeError(
        f"Expected 25 holdout subjects, found {len(holdout_subjects)}"
    )


# ============================================================
# FIND ORIGINAL 130 FILES
# ============================================================

source_files = find_processed_csvs(SOURCE_DIR)

print("Original processed files:", len(source_files))

subject_to_files = {}
original_subject_ids = {}

for file_path in source_files:

    parsed = _subject_from_filename(file_path)
    normalized = norm_subject(parsed)

    subject_to_files.setdefault(
        normalized, []
    ).append(file_path)

    original_subject_ids[normalized] = str(parsed)


# ============================================================
# MASTER COLUMN ORDER
# ============================================================

first_frame = _read_csv_with_retries(source_files[0])

master_source_columns = list(first_frame.columns)
master_columns = list(master_source_columns)

for col in ["subject_split", "sample_split"]:
    if col not in master_columns:
        master_columns.append(col)

del first_frame


local_outputs = {
    "train": LOCAL_TRAIN,
    "validation": LOCAL_VALIDATION,
    "holdout": LOCAL_HOLDOUT,
}

epoch_counts = {
    "train": 0,
    "validation": 0,
    "holdout": 0,
}

row_counts = {
    "train": 0,
    "validation": 0,
    "holdout": 0,
}

subjects_written = {
    "train": set(),
    "validation": set(),
    "holdout": set(),
}


# ============================================================
# REBUILD ALL 25 HOLDOUT SUBJECTS FROM ORIGINAL DATA
# ============================================================

for number, subject_id in enumerate(
    holdout_subjects,
    start=1
):

    print(
        f"\nRebuilding holdout "
        f"{number}/25: sub-{subject_id.zfill(3)}"
    )

    if subject_id not in subject_to_files:
        raise RuntimeError(
            f"No source files found for subject {subject_id}"
        )

    frames = []

    for file_path in subject_to_files[subject_id]:

        frame = _read_csv_with_retries(file_path)

        frame = _normalize_source_frame(
            frame,
            file_path,
            master_source_columns,
        )

        frames.append(frame)

    subject_data = pd.concat(
        frames,
        ignore_index=True
    )

    del frames


    # Complete 24-row epochs only
    counts = subject_data.groupby("epoch_uid").size()

    valid_epoch_ids = (
        counts[counts == 24]
        .index
        .tolist()
    )

    subject_data = subject_data[
        subject_data["epoch_uid"].isin(valid_epoch_ids)
    ].copy()


    # EXACT SAME ORIGINAL PER-SUBJECT SEED
    seed_subject = original_subject_ids[subject_id]

    split_seed = (
        RANDOM_STATE
        + sum(ord(c) for c in seed_subject)
    )

    split_ids = _split_epoch_ids(
        valid_epoch_ids,
        FRACTIONS,
        split_seed,
    )


    # Verify assignment
    assigned = [
        epoch
        for ids in split_ids.values()
        for epoch in ids
    ]

    if len(assigned) != len(set(assigned)):
        raise RuntimeError(
            f"Epoch overlap for subject {subject_id}"
        )

    if set(assigned) != set(valid_epoch_ids):
        raise RuntimeError(
            f"Missing epoch assignment for subject {subject_id}"
        )


    # Write all three locally
    for split_name, ids in split_ids.items():

        split_frame = subject_data[
            subject_data["epoch_uid"].isin(ids)
        ].copy()

        split_frame["subject_split"] = "subject_holdout"
        split_frame["sample_split"] = split_name

        _append_frame(
            split_frame,
            local_outputs[split_name],
            master_columns,
        )

        subjects_written[split_name].add(subject_id)
        epoch_counts[split_name] += len(ids)
        row_counts[split_name] += len(split_frame)

        print(
            f"  {split_name}: "
            f"{len(ids)} epochs / "
            f"{len(split_frame)} rows"
        )

    del subject_data


# ============================================================
# VERIFY WITHOUT CHUNK-BOUNDARY FALSE ERRORS
# ============================================================

print("\n" + "=" * 70)
print("LOCAL HOLDOUT REBUILD COMPLETE")
print("=" * 70)

for split_name in [
    "train",
    "validation",
    "holdout",
]:

    subjects = subjects_written[split_name]
    epochs = epoch_counts[split_name]
    rows = row_counts[split_name]

    print(
        f"{split_name}: "
        f"{len(subjects)} subjects | "
        f"{epochs} epochs | "
        f"{rows} rows"
    )

    if len(subjects) != 25:
        raise RuntimeError(
            f"{split_name}: expected 25 subjects, "
            f"got {len(subjects)}"
        )

    if rows != epochs * 24:
        raise RuntimeError(
            f"{split_name}: rows != epochs × 24"
        )

print("\nPASS — all 25 subjects rebuilt correctly.")


# ============================================================
# COPY COMPLETE FILES TO DRIVE
# ============================================================

DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

pairs = [
    (LOCAL_TRAIN, DRIVE_TRAIN),
    (LOCAL_VALIDATION, DRIVE_VALIDATION),
    (LOCAL_HOLDOUT, DRIVE_HOLDOUT),
]

print("\nCopying completed files to Drive...")

for local_path, drive_path in pairs:

    shutil.copy2(
        local_path,
        drive_path
    )

    os.sync()
    time.sleep(3)

    if not drive_path.exists():
        raise RuntimeError(
            f"Missing after copy: {drive_path}"
        )

    if (
        local_path.stat().st_size
        != drive_path.stat().st_size
    ):
        raise RuntimeError(
            f"Size mismatch: {drive_path}"
        )

    print(
        drive_path.name,
        "PASS |",
        round(
            drive_path.stat().st_size / (1024 ** 3),
            3
        ),
        "GB"
    )


print("\n" + "=" * 70)
print("3B HOLDOUT REBUILD COMPLETE")
print("=" * 70)

print(
    "All 25 holdout subjects now have "
    "train / validation / holdout data."
)

3B functions loaded.
Holdout subjects: 25
['086', '071', '047', '098', '092', '078', '032', '072', '060', '089', '033', '094', '039', '046', '084', '057', '075', '063', '061', '082', '064', '040', '049', '041', '050']
Original processed files: 130

Rebuilding holdout 1/25: sub-086
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Rebuilding holdout 2/25: sub-071
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Rebuilding holdout 3/25: sub-047
  train: 808 epochs / 19392 rows
  validation: 404 epochs / 9696 rows
  holdout: 405 epochs / 9720 rows

Rebuilding holdout 4/25: sub-098
  train: 786 epochs / 18864 rows
  validation: 393 epochs / 9432 rows
  holdout: 393 epochs / 9432 rows

Rebuilding holdout 5/25: sub-092
  train: 796 epochs / 19104 rows
  validation: 398 epochs / 9552 rows
  holdout: 397 epochs / 9528 rows

Rebuilding holdout 6/25: sub-078
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Rebuilding holdout 7/25: sub-032
  train: 786 epochs / 18864 rows
  validation: 393 epochs / 9432 rows
  holdout: 392 epochs / 9408 rows

Rebuilding holdout 8/25: sub-072
  train: 780 epochs / 18720 rows
  validation: 390 epochs / 9360 rows
  holdout: 390 epochs / 9360 rows

Rebuilding holdout 9/25: sub-060
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 397 epochs / 9528 rows

Rebuilding holdout 10/25: sub-089
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 397 epochs / 9528 rows

Rebuilding holdout 11/25: sub-033
  train: 775 epochs / 18600 rows
  validation: 388 epochs / 9312 rows
  holdout: 387 epochs / 9288 rows

Rebuilding holdout 12/25: sub-094
  train: 710 epochs / 17040 rows
  validation: 355 epochs / 8520 rows
  holdout: 355 epochs / 8520 rows

Rebuilding holdout 13/25: sub-039
  train: 788 epochs / 18912 rows
  validation: 394 epochs / 9456 rows
  holdout: 394 epochs / 9456 rows

Rebuilding holdout 14/25: sub-046
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 396 epochs / 9504 rows

Rebuilding holdout 15/25: sub-084
  train: 791 epochs / 18984 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Rebuilding holdout 16/25: sub-057
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Rebuilding holdout 17/25: sub-075
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 397 epochs / 9528 rows

Rebuilding holdout 18/25: sub-063
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Rebuilding holdout 19/25: sub-061
  train: 793 epochs / 19032 rows
  validation: 396 epochs / 9504 rows
  holdout: 397 epochs / 9528 rows

Rebuilding holdout 20/25: sub-082
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Rebuilding holdout 21/25: sub-064
  train: 791 epochs / 18984 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Rebuilding holdout 22/25: sub-040
  train: 783 epochs / 18792 rows
  validation: 392 epochs / 9408 rows
  holdout: 391 epochs / 9384 rows

Rebuilding holdout 23/25: sub-049
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Rebuilding holdout 24/25: sub-041
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 398 epochs / 9552 rows

Rebuilding holdout 25/25: sub-050
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

======================================================================
LOCAL HOLDOUT REBUILD COMPLETE
======================================================================
train: 25 subjects | 19670 epochs | 472080 rows
validation: 25 subjects | 9836 epochs | 236064 rows
holdout: 25 subjects | 9833 epochs | 235992 rows

PASS — all 25 subjects rebuilt correctly.

Copying completed files to Drive...
train.csv PASS | 1.046 GB
validation.csv PASS | 0.524 GB
holdout.csv PASS | 0.523 GB

======================================================================
3B HOLDOUT REBUILD COMPLETE
======================================================================
All 25 holdout subjects now have train / validation / holdout data.

In [ ]:
import sys, importlib
code_folder = '/content/drive/MyDrive/EEG Shared/Code/Code Luke'
if code_folder not in sys.path:
    sys.path.insert(0, code_folder)
import load_data_3b_exact_40_25_split_50_25_25
importlib.reload(load_data_3b_exact_40_25_split_50_25_25)
from load_data_3b_exact_40_25_split_50_25_25 import build_exact_subject_split

In [ ]:
directory_name = '/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects'

output_directory = '/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split'

DEVELOPMENT_SUBJECTS = 40
HOLDOUT_SUBJECTS = 25

# EVERY subject:
# 50% train / 25% validation / 25% holdout
DEVELOPMENT_TRAIN_FRACTION = 0.50
DEVELOPMENT_VALIDATION_FRACTION = 0.25

HOLDOUT_TRAIN_FRACTION = 0.50
HOLDOUT_VALIDATION_FRACTION = 0.25

RANDOM_STATE = 1

In [ ]:
# ============================================================
# FULL 3B DEVELOPMENT REPAIR
#
# Rebuilds:
#   subject_train/train.csv
#   subject_train/validation.csv
#   subject_train/holdout.csv
#
# Leaves subject_holdout completely untouched.
# Builds locally first, verifies, THEN copies to Google Drive.
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np
import sys
import importlib
import shutil
import os
import time


# ============================================================
# PATHS
# ============================================================

CODE_DIR = Path(
    "/content/drive/MyDrive/EEG Shared/Code/Code Luke"
)

SOURCE_DIR = Path(
    "/content/drive/MyDrive/EEG Shared/Processed_data/"
    "Kosachenko_All_Subjects"
)

OUTPUT_DIR = (
    SOURCE_DIR /
    "3B_Exact_40_25_Split"
)

MANIFEST_PATH = (
    OUTPUT_DIR /
    "subject_assignments.csv"
)

DRIVE_TRAIN = (
    OUTPUT_DIR /
    "subject_train" /
    "train.csv"
)

DRIVE_VALIDATION = (
    OUTPUT_DIR /
    "subject_train" /
    "validation.csv"
)

DRIVE_HOLDOUT = (
    OUTPUT_DIR /
    "subject_train" /
    "holdout.csv"
)


# Build all 3 locally first
LOCAL_DIR = Path(
    "/content/3b_development_repair"
)

LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

LOCAL_TRAIN = (
    LOCAL_DIR /
    "train.csv"
)

LOCAL_VALIDATION = (
    LOCAL_DIR /
    "validation.csv"
)

LOCAL_HOLDOUT = (
    LOCAL_DIR /
    "holdout.csv"
)


# ============================================================
# LOAD ORIGINAL 3B FUNCTIONS
# ============================================================

if str(CODE_DIR) not in sys.path:
    sys.path.insert(
        0,
        str(CODE_DIR)
    )

module_name = (
    "load_data_3b_exact_40_25_split_50_25_25"
)

m = importlib.import_module(
    module_name
)

m = importlib.reload(m)

_read_csv_with_retries = (
    m._read_csv_with_retries
)

_subject_from_filename = (
    m._subject_from_filename
)

_normalize_source_frame = (
    m._normalize_source_frame
)

_split_epoch_ids = (
    m._split_epoch_ids
)

_append_frame = (
    m._append_frame
)

find_processed_csvs = (
    m.find_processed_csvs
)

print("3B functions loaded.")


# ============================================================
# SETTINGS
# ============================================================

RANDOM_STATE = 1

FRACTIONS = {
    "train": 0.50,
    "validation": 0.25,
    "holdout": 0.25,
}


# ============================================================
# SUBJECT NORMALIZATION
# ============================================================

def normalize_subject_id(value):

    s = str(value).strip()

    if s.endswith(".0"):
        s = s[:-2]

    if s.isdigit():
        return str(int(s))

    return s


# ============================================================
# REMOVE OLD LOCAL REPAIR FILES
# ============================================================

for path in [
    LOCAL_TRAIN,
    LOCAL_VALIDATION,
    LOCAL_HOLDOUT,
]:

    if path.exists():
        path.unlink()


# ============================================================
# LOAD EXACT 40 DEVELOPMENT SUBJECT ASSIGNMENTS
# ============================================================

if not MANIFEST_PATH.exists():

    raise FileNotFoundError(
        f"Missing manifest:\n"
        f"{MANIFEST_PATH}"
    )


manifest = pd.read_csv(
    MANIFEST_PATH
)


development_subjects = [

    normalize_subject_id(x)

    for x in manifest.loc[
        manifest[
            "subject_split"
        ] == "subject_train",
        "subject_id"
    ].tolist()
]


print(
    "Development subjects:",
    len(development_subjects)
)


if len(development_subjects) != 40:

    raise RuntimeError(
        "Expected exactly 40 "
        "development subjects."
    )


# ============================================================
# FIND ORIGINAL 130 PROCESSED FILES
# ============================================================

source_files = (
    find_processed_csvs(
        SOURCE_DIR
    )
)

print(
    "Original processed files:",
    len(source_files)
)


if len(source_files) != 130:

    print(
        "WARNING: expected 130 "
        "processed files, found",
        len(source_files)
    )


# ============================================================
# MAP ORIGINAL FILES TO SUBJECTS
#
# Preserve original zero-padded ID for deterministic seed:
# 51 -> original ID "051"
# ============================================================

subject_to_files = {}

original_subject_id = {}


for file_path in source_files:

    parsed = _subject_from_filename(
        file_path
    )

    normalized = normalize_subject_id(
        parsed
    )

    subject_to_files.setdefault(
        normalized,
        []
    ).append(file_path)

    original_subject_id[
        normalized
    ] = str(parsed)


print(
    "Subjects found in originals:",
    len(subject_to_files)
)


# ============================================================
# MASTER COLUMN SCHEMA
# ============================================================

first_frame = (
    _read_csv_with_retries(
        source_files[0]
    )
)

master_source_columns = list(
    first_frame.columns
)

master_columns = list(
    master_source_columns
)

for column in [
    "subject_split",
    "sample_split",
]:

    if column not in master_columns:
        master_columns.append(
            column
        )

del first_frame


# ============================================================
# OUTPUT PATH MAP
# ============================================================

local_outputs = {

    "train":
        LOCAL_TRAIN,

    "validation":
        LOCAL_VALIDATION,

    "holdout":
        LOCAL_HOLDOUT,
}


# ============================================================
# COUNTS FOR VERIFICATION
# ============================================================

epoch_counts = {

    "train": 0,
    "validation": 0,
    "holdout": 0,
}

row_counts = {

    "train": 0,
    "validation": 0,
    "holdout": 0,
}

subjects_written = {

    "train": set(),
    "validation": set(),
    "holdout": set(),
}


# ============================================================
# REBUILD ALL 40 DEVELOPMENT SUBJECTS
# ============================================================

for number, subject_id in enumerate(
    development_subjects,
    start=1
):

    print(
        f"\nRepairing "
        f"{number}/40: "
        f"{subject_id.zfill(3)}"
    )

    if subject_id not in subject_to_files:

        raise RuntimeError(
            f"No source files for "
            f"subject {subject_id}"
        )


    # --------------------------------------------------------
    # LOAD THIS SUBJECT ONLY
    # --------------------------------------------------------

    frames = []

    for file_path in (
        subject_to_files[
            subject_id
        ]
    ):

        frame = (
            _read_csv_with_retries(
                file_path
            )
        )

        frame = (
            _normalize_source_frame(
                frame,
                file_path,
                master_source_columns,
            )
        )

        frames.append(
            frame
        )


    subject_data = pd.concat(
        frames,
        ignore_index=True
    )

    del frames


    # --------------------------------------------------------
    # COMPLETE EPOCHS ONLY
    # --------------------------------------------------------

    counts = (
        subject_data
        .groupby(
            "epoch_uid"
        )
        .size()
    )

    valid_epoch_ids = (
        counts[
            counts == 24
        ]
        .index
        .tolist()
    )


    incomplete = int(
        (
            counts != 24
        ).sum()
    )

    if incomplete:

        print(
            "  dropping",
            incomplete,
            "incomplete epochs"
        )


    subject_data = (
        subject_data[
            subject_data[
                "epoch_uid"
            ].isin(
                valid_epoch_ids
            )
        ]
        .copy()
    )


    # --------------------------------------------------------
    # EXACT SAME DETERMINISTIC SPLIT
    # AS ORIGINAL 3B
    # --------------------------------------------------------

    seed_subject = (
        original_subject_id[
            subject_id
        ]
    )

    split_seed = (
        RANDOM_STATE
        +
        sum(
            ord(c)
            for c in seed_subject
        )
    )


    split_ids = (
        _split_epoch_ids(
            valid_epoch_ids,
            FRACTIONS,
            split_seed,
        )
    )


    # --------------------------------------------------------
    # VERIFY NO OVERLAP
    # --------------------------------------------------------

    all_assigned = [

        epoch

        for ids
        in split_ids.values()

        for epoch
        in ids
    ]


    if (
        len(all_assigned)
        !=
        len(
            set(all_assigned)
        )
    ):

        raise RuntimeError(
            f"Epoch overlap for "
            f"subject {subject_id}"
        )


    if (
        set(all_assigned)
        !=
        set(valid_epoch_ids)
    ):

        raise RuntimeError(
            f"Not every epoch assigned "
            f"for subject {subject_id}"
        )


    # --------------------------------------------------------
    # WRITE TRAIN / VALIDATION / HOLDOUT LOCALLY
    # --------------------------------------------------------

    for split_name in [
        "train",
        "validation",
        "holdout",
    ]:

        ids = (
            split_ids[
                split_name
            ]
        )


        split_frame = (
            subject_data[
                subject_data[
                    "epoch_uid"
                ].isin(ids)
            ]
            .copy()
        )


        split_frame[
            "subject_split"
        ] = "subject_train"

        split_frame[
            "sample_split"
        ] = split_name


        # Every epoch must still be 24 rows
        split_sizes = (
            split_frame
            .groupby(
                "epoch_uid"
            )
            .size()
        )

        bad_sizes = (
            split_sizes[
                split_sizes != 24
            ]
        )

        if len(bad_sizes):

            raise RuntimeError(
                f"{subject_id} / "
                f"{split_name}: "
                f"bad epoch sizes"
            )


        _append_frame(
            split_frame,
            local_outputs[
                split_name
            ],
            master_columns,
        )


        epoch_counts[
            split_name
        ] += len(ids)

        row_counts[
            split_name
        ] += len(
            split_frame
        )

        subjects_written[
            split_name
        ].add(
            subject_id
        )


        print(
            f"  {split_name}: "
            f"{len(ids)} epochs / "
            f"{len(split_frame)} rows"
        )


    del subject_data


# ============================================================
# LOCAL VERIFICATION
# ============================================================

print(
    "\n"
    + "=" * 70
)

print(
    "LOCAL REBUILD COMPLETE"
)

print(
    "=" * 70
)


for split_name in [
    "train",
    "validation",
    "holdout",
]:

    print(
        f"\n{split_name.upper()}"
    )

    print(
        "Subjects:",
        len(
            subjects_written[
                split_name
            ]
        )
    )

    print(
        "Epochs:",
        epoch_counts[
            split_name
        ]
    )

    print(
        "Rows:",
        row_counts[
            split_name
        ]
    )

    print(
        "Expected rows:",
        epoch_counts[
            split_name
        ] * 24
    )


    if (
        len(
            subjects_written[
                split_name
            ]
        )
        != 40
    ):

        raise RuntimeError(
            f"{split_name} does not "
            f"contain all 40 subjects."
        )


    if (
        row_counts[
            split_name
        ]
        !=
        epoch_counts[
            split_name
        ] * 24
    ):

        raise RuntimeError(
            f"{split_name} row count "
            f"is not epochs × 24."
        )


    if not (
        local_outputs[
            split_name
        ].exists()
    ):

        raise RuntimeError(
            f"Local {split_name}.csv "
            f"was not created."
        )


print(
    "\nPASS — all 3 local "
    "development files verified."
)


# ============================================================
# COPY COMPLETED FILES TO GOOGLE DRIVE
# ============================================================

print(
    "\nCopying completed files "
    "to Google Drive..."
)


DRIVE_TRAIN.parent.mkdir(
    parents=True,
    exist_ok=True
)


copy_pairs = [

    (
        LOCAL_TRAIN,
        DRIVE_TRAIN
    ),

    (
        LOCAL_VALIDATION,
        DRIVE_VALIDATION
    ),

    (
        LOCAL_HOLDOUT,
        DRIVE_HOLDOUT
    ),
]


for local_path, drive_path in (
    copy_pairs
):

    print(
        "\nCopying:",
        local_path.name
    )

    print(
        "Local size:",
        local_path.stat().st_size
    )


    shutil.copy2(
        local_path,
        drive_path
    )


    os.sync()
    time.sleep(3)


    if not drive_path.exists():

        raise RuntimeError(
            f"Drive copy missing: "
            f"{drive_path}"
        )


    local_size = (
        local_path
        .stat()
        .st_size
    )

    drive_size = (
        drive_path
        .stat()
        .st_size
    )


    print(
        "Drive size:",
        drive_size
    )


    if (
        local_size
        !=
        drive_size
    ):

        raise RuntimeError(
            f"Size mismatch for "
            f"{drive_path.name}"
        )


    print(
        "  PASS"
    )


# ============================================================
# FINAL
# ============================================================

print(
    "\n"
    + "=" * 70
)

print(
    "3B DEVELOPMENT REPAIR COMPLETE"
)

print(
    "=" * 70
)

print(
    "All 40 development subjects "
    "are now present in:"
)

print(
    "  train.csv"
)

print(
    "  validation.csv"
)

print(
    "  holdout.csv"
)

print(
    "\nAll epochs remain "
    "exactly 24 rows."
)

print(
    "\nYou can now rerun 3C."
)

3B functions loaded.
Development subjects: 40
Original processed files: 130
Subjects found in originals: 65

Repairing 1/40: 051
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 397 epochs / 9528 rows

Repairing 2/40: 079
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 398 epochs / 9552 rows

Repairing 3/40: 045
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Repairing 4/40: 035
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 396 epochs / 9504 rows

Repairing 5/40: 091
  train: 796 epochs / 19104 rows
  validation: 398 epochs / 9552 rows
  holdout: 398 epochs / 9552 rows

Repairing 6/40: 074
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Repairing 7/40: 052
  train: 788 epochs / 18912 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Repairing 8/40: 038
  train: 784 epochs / 18816 rows
  validation: 392 epochs / 9408 rows
  holdout: 392 epochs / 9408 rows

Repairing 9/40: 054
  train: 802 epochs / 19248 rows
  validation: 401 epochs / 9624 rows
  holdout: 401 epochs / 9624 rows

Repairing 10/40: 036
  train: 788 epochs / 18912 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Repairing 11/40: 034
  train: 782 epochs / 18768 rows
  validation: 391 epochs / 9384 rows
  holdout: 391 epochs / 9384 rows

Repairing 12/40: 070
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Repairing 13/40: 043
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Repairing 14/40: 097
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Repairing 15/40: 059
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Repairing 16/40: 065
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 396 epochs / 9504 rows

Repairing 17/40: 062
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 396 epochs / 9504 rows

Repairing 18/40: 042
  train: 802 epochs / 19248 rows
  validation: 401 epochs / 9624 rows
  holdout: 402 epochs / 9648 rows

Repairing 19/40: 058
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Repairing 20/40: 073
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 396 epochs / 9504 rows

Repairing 21/40: 055
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Repairing 22/40: 044
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 396 epochs / 9504 rows

Repairing 23/40: 085
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 396 epochs / 9504 rows

Repairing 24/40: 077
  train: 793 epochs / 19032 rows
  validation: 396 epochs / 9504 rows
  holdout: 397 epochs / 9528 rows

Repairing 25/40: 048
  train: 800 epochs / 19200 rows
  validation: 400 epochs / 9600 rows
  holdout: 401 epochs / 9624 rows

Repairing 26/40: 076
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Repairing 27/40: 067
  train: 795 epochs / 19080 rows
  validation: 398 epochs / 9552 rows
  holdout: 397 epochs / 9528 rows

Repairing 28/40: 095
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Repairing 29/40: 096
  train: 798 epochs / 19152 rows
  validation: 399 epochs / 9576 rows
  holdout: 400 epochs / 9600 rows

Repairing 30/40: 069
  train: 804 epochs / 19296 rows
  validation: 402 epochs / 9648 rows
  holdout: 403 epochs / 9672 rows

Repairing 31/40: 056
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 396 epochs / 9504 rows

Repairing 32/40: 093
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 396 epochs / 9504 rows

Repairing 33/40: 087
  train: 791 epochs / 18984 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Repairing 34/40: 083
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Repairing 35/40: 080
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Repairing 36/40: 068
  train: 796 epochs / 19104 rows
  validation: 398 epochs / 9552 rows
  holdout: 397 epochs / 9528 rows

Repairing 37/40: 090
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Repairing 38/40: 081
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Repairing 39/40: 088
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 396 epochs / 9504 rows

Repairing 40/40: 053
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 396 epochs / 9504 rows

======================================================================
LOCAL REBUILD COMPLETE
======================================================================

TRAIN
Subjects: 40
Epochs: 31687
Rows: 760488
Expected rows: 760488

VALIDATION
Subjects: 40
Epochs: 15842
Rows: 380208
Expected rows: 380208

HOLDOUT
Subjects: 40
Epochs: 15847
Rows: 380328
Expected rows: 380328

PASS — all 3 local development files verified.

Copying completed files to Google Drive...

Copying: train.csv
Local size: 1807477159
Drive size: 1807477159
  PASS

Copying: validation.csv
Local size: 905468665
Drive size: 905468665
  PASS

Copying: holdout.csv
Local size: 904632940
Drive size: 904632940
  PASS

======================================================================
3B DEVELOPMENT REPAIR COMPLETE
======================================================================
All 40 development subjects are now present in:
  train.csv
  validation.csv
  holdout.csv

All epochs remain exactly 24 rows.

You can now rerun 3C.

In [ ]:
results = build_exact_subject_split(
    directory_name=directory_name,
    output_directory=output_directory,
    development_subject_count=DEVELOPMENT_SUBJECTS,
    holdout_subject_count=HOLDOUT_SUBJECTS,
    development_train_fraction=DEVELOPMENT_TRAIN_FRACTION,
    development_validation_fraction=DEVELOPMENT_VALIDATION_FRACTION,
    holdout_train_fraction=HOLDOUT_TRAIN_FRACTION,
    holdout_validation_fraction=HOLDOUT_VALIDATION_FRACTION,
    random_state=RANDOM_STATE,
    overwrite=True,
)

Discovering subjects...
Indexing file 1/130: sub-032_task-memory_eeg_processed.csv
Indexing file 2/130: sub-032_task-rest_eeg_processed.csv
Indexing file 3/130: sub-033_task-memory_eeg_processed.csv
Indexing file 4/130: sub-033_task-rest_eeg_processed.csv
Indexing file 5/130: sub-034_task-memory_eeg_processed.csv
Indexing file 6/130: sub-034_task-rest_eeg_processed.csv
Indexing file 7/130: sub-035_task-memory_eeg_processed.csv
Indexing file 8/130: sub-035_task-rest_eeg_processed.csv
Indexing file 9/130: sub-036_task-memory_eeg_processed.csv
Indexing file 10/130: sub-036_task-rest_eeg_processed.csv
Indexing file 11/130: sub-038_task-memory_eeg_processed.csv
Indexing file 12/130: sub-038_task-rest_eeg_processed.csv
Indexing file 13/130: sub-039_task-memory_eeg_processed.csv
Indexing file 14/130: sub-039_task-rest_eeg_processed.csv
Indexing file 15/130: sub-040_task-memory_eeg_processed.csv
Indexing file 16/130: sub-040_task-rest_eeg_processed.csv
Indexing file 17/130: sub-041_task-memory_eeg_processed.csv
Indexing file 18/130: sub-041_task-rest_eeg_processed.csv
Indexing file 19/130: sub-042_task-memory_eeg_processed.csv
Indexing file 20/130: sub-042_task-rest_eeg_processed.csv
Indexing file 21/130: sub-043_task-memory_eeg_processed.csv
Indexing file 22/130: sub-043_task-rest_eeg_processed.csv
Indexing file 23/130: sub-044_task-memory_eeg_processed.csv
Indexing file 24/130: sub-044_task-rest_eeg_processed.csv
Indexing file 25/130: sub-045_task-memory_eeg_processed.csv
Indexing file 26/130: sub-045_task-rest_eeg_processed.csv
Indexing file 27/130: sub-046_task-memory_eeg_processed.csv
Indexing file 28/130: sub-046_task-rest_eeg_processed.csv
Indexing file 29/130: sub-047_task-memory_eeg_processed.csv
Indexing file 30/130: sub-047_task-rest_eeg_processed.csv
Indexing file 31/130: sub-048_task-memory_eeg_processed.csv
Indexing file 32/130: sub-048_task-rest_eeg_processed.csv
Indexing file 33/130: sub-049_task-memory_eeg_processed.csv
Indexing file 34/130: sub-049_task-rest_eeg_processed.csv
Indexing file 35/130: sub-050_task-memory_eeg_processed.csv
Indexing file 36/130: sub-050_task-rest_eeg_processed.csv
Indexing file 37/130: sub-051_task-memory_eeg_processed.csv
Indexing file 38/130: sub-051_task-rest_eeg_processed.csv
Indexing file 39/130: sub-052_task-memory_eeg_processed.csv
Indexing file 40/130: sub-052_task-rest_eeg_processed.csv
Indexing file 41/130: sub-053_task-memory_eeg_processed.csv
Indexing file 42/130: sub-053_task-rest_eeg_processed.csv
Indexing file 43/130: sub-054_task-memory_eeg_processed.csv
Indexing file 44/130: sub-054_task-rest_eeg_processed.csv
Indexing file 45/130: sub-055_task-memory_eeg_processed.csv
Indexing file 46/130: sub-055_task-rest_eeg_processed.csv
Indexing file 47/130: sub-056_task-memory_eeg_processed.csv
Indexing file 48/130: sub-056_task-rest_eeg_processed.csv
Indexing file 49/130: sub-057_task-memory_eeg_processed.csv
Indexing file 50/130: sub-057_task-rest_eeg_processed.csv
Indexing file 51/130: sub-058_task-memory_eeg_processed.csv
Indexing file 52/130: sub-058_task-rest_eeg_processed.csv
Indexing file 53/130: sub-059_task-memory_eeg_processed.csv
Indexing file 54/130: sub-059_task-rest_eeg_processed.csv
Indexing file 55/130: sub-060_task-memory_eeg_processed.csv
Indexing file 56/130: sub-060_task-rest_eeg_processed.csv
Indexing file 57/130: sub-061_task-memory_eeg_processed.csv
Indexing file 58/130: sub-061_task-rest_eeg_processed.csv
Indexing file 59/130: sub-062_task-memory_eeg_processed.csv
Indexing file 60/130: sub-062_task-rest_eeg_processed.csv
Indexing file 61/130: sub-063_task-memory_eeg_processed.csv
Indexing file 62/130: sub-063_task-rest_eeg_processed.csv
Indexing file 63/130: sub-064_task-memory_eeg_processed.csv
Indexing file 64/130: sub-064_task-rest_eeg_processed.csv
Indexing file 65/130: sub-065_task-memory_eeg_processed.csv
Indexing file 66/130: sub-065_task-rest_eeg_processed.csv
Indexing file 67/130: sub-067_task-memory_eeg_processed.csv
Indexing file 68/130: sub-067_task-rest_eeg_processed.csv
Indexing file 69/130: sub-068_task-memory_eeg_processed.csv
Indexing file 70/130: sub-068_task-rest_eeg_processed.csv
Indexing file 71/130: sub-069_task-memory_eeg_processed.csv
Indexing file 72/130: sub-069_task-rest_eeg_processed.csv
Indexing file 73/130: sub-070_task-memory_eeg_processed.csv
Indexing file 74/130: sub-070_task-rest_eeg_processed.csv
Indexing file 75/130: sub-071_task-memory_eeg_processed.csv
Indexing file 76/130: sub-071_task-rest_eeg_processed.csv
Indexing file 77/130: sub-072_task-memory_eeg_processed.csv
Indexing file 78/130: sub-072_task-rest_eeg_processed.csv
Indexing file 79/130: sub-073_task-memory_eeg_processed.csv
Indexing file 80/130: sub-073_task-rest_eeg_processed.csv
Indexing file 81/130: sub-074_task-memory_eeg_processed.csv
Indexing file 82/130: sub-074_task-rest_eeg_processed.csv
Indexing file 83/130: sub-075_task-memory_eeg_processed.csv
Indexing file 84/130: sub-075_task-rest_eeg_processed.csv
Indexing file 85/130: sub-076_task-memory_eeg_processed.csv
Indexing file 86/130: sub-076_task-rest_eeg_processed.csv
Indexing file 87/130: sub-077_task-memory_eeg_processed.csv
Indexing file 88/130: sub-077_task-rest_eeg_processed.csv
Indexing file 89/130: sub-078_task-memory_eeg_processed.csv
Indexing file 90/130: sub-078_task-rest_eeg_processed.csv
Indexing file 91/130: sub-079_task-memory_eeg_processed.csv
Indexing file 92/130: sub-079_task-rest_eeg_processed.csv
Indexing file 93/130: sub-080_task-memory_eeg_processed.csv
Indexing file 94/130: sub-080_task-rest_eeg_processed.csv
Indexing file 95/130: sub-081_task-memory_eeg_processed.csv
Indexing file 96/130: sub-081_task-rest_eeg_processed.csv
Indexing file 97/130: sub-082_task-memory_eeg_processed.csv
Indexing file 98/130: sub-082_task-rest_eeg_processed.csv
Indexing file 99/130: sub-083_task-memory_eeg_processed.csv
Indexing file 100/130: sub-083_task-rest_eeg_processed.csv
Indexing file 101/130: sub-084_task-memory_eeg_processed.csv
Indexing file 102/130: sub-084_task-rest_eeg_processed.csv
Indexing file 103/130: sub-085_task-memory_eeg_processed.csv
Indexing file 104/130: sub-085_task-rest_eeg_processed.csv
Indexing file 105/130: sub-086_task-memory_eeg_processed.csv
Indexing file 106/130: sub-086_task-rest_eeg_processed.csv
Indexing file 107/130: sub-087_task-memory_eeg_processed.csv
Indexing file 108/130: sub-087_task-rest_eeg_processed.csv
Indexing file 109/130: sub-088_task-memory_eeg_processed.csv
Indexing file 110/130: sub-088_task-rest_eeg_processed.csv
Indexing file 111/130: sub-089_task-memory_eeg_processed.csv
Indexing file 112/130: sub-089_task-rest_eeg_processed.csv
Indexing file 113/130: sub-090_task-memory_eeg_processed.csv
Indexing file 114/130: sub-090_task-rest_eeg_processed.csv
Indexing file 115/130: sub-091_task-memory_eeg_processed.csv
Indexing file 116/130: sub-091_task-rest_eeg_processed.csv
Indexing file 117/130: sub-092_task-memory_eeg_processed.csv
Indexing file 118/130: sub-092_task-rest_eeg_processed.csv
Indexing file 119/130: sub-093_task-memory_eeg_processed.csv
Indexing file 120/130: sub-093_task-rest_eeg_processed.csv
Indexing file 121/130: sub-094_task-memory_eeg_processed.csv
Indexing file 122/130: sub-094_task-rest_eeg_processed.csv
Indexing file 123/130: sub-095_task-memory_eeg_processed.csv
Indexing file 124/130: sub-095_task-rest_eeg_processed.csv
Indexing file 125/130: sub-096_task-memory_eeg_processed.csv
Indexing file 126/130: sub-096_task-rest_eeg_processed.csv
Indexing file 127/130: sub-097_task-memory_eeg_processed.csv
Indexing file 128/130: sub-097_task-rest_eeg_processed.csv
Indexing file 129/130: sub-098_task-memory_eeg_processed.csv
Indexing file 130/130: sub-098_task-rest_eeg_processed.csv

Subject split:
Development subjects: 40
Holdout subjects: 25

Subject 1/65: 051 -> subject_train
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 397 epochs / 9528 rows

Subject 2/65: 079 -> subject_train
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 398 epochs / 9552 rows

Subject 3/65: 045 -> subject_train
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Subject 4/65: 035 -> subject_train
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 396 epochs / 9504 rows

Subject 5/65: 091 -> subject_train
  train: 796 epochs / 19104 rows
  validation: 398 epochs / 9552 rows
  holdout: 398 epochs / 9552 rows

Subject 6/65: 074 -> subject_train
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Subject 7/65: 052 -> subject_train
  train: 788 epochs / 18912 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Subject 8/65: 038 -> subject_train
  train: 784 epochs / 18816 rows
  validation: 392 epochs / 9408 rows
  holdout: 392 epochs / 9408 rows

Subject 9/65: 054 -> subject_train
  train: 802 epochs / 19248 rows
  validation: 401 epochs / 9624 rows
  holdout: 401 epochs / 9624 rows

Subject 10/65: 036 -> subject_train
  train: 788 epochs / 18912 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Subject 11/65: 034 -> subject_train
  train: 782 epochs / 18768 rows
  validation: 391 epochs / 9384 rows
  holdout: 391 epochs / 9384 rows

Subject 12/65: 070 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Subject 13/65: 043 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 14/65: 097 -> subject_train
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Subject 15/65: 059 -> subject_train
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Subject 16/65: 065 -> subject_train
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 396 epochs / 9504 rows

Subject 17/65: 062 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 396 epochs / 9504 rows

Subject 18/65: 042 -> subject_train
  train: 802 epochs / 19248 rows
  validation: 401 epochs / 9624 rows
  holdout: 402 epochs / 9648 rows

Subject 19/65: 058 -> subject_train
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Subject 20/65: 073 -> subject_train
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 396 epochs / 9504 rows

Subject 21/65: 055 -> subject_train
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Subject 22/65: 044 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 396 epochs / 9504 rows

Subject 23/65: 085 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 396 epochs / 9504 rows

Subject 24/65: 077 -> subject_train
  train: 793 epochs / 19032 rows
  validation: 396 epochs / 9504 rows
  holdout: 397 epochs / 9528 rows

Subject 25/65: 048 -> subject_train
  train: 800 epochs / 19200 rows
  validation: 400 epochs / 9600 rows
  holdout: 401 epochs / 9624 rows

Subject 26/65: 076 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 27/65: 067 -> subject_train
  train: 795 epochs / 19080 rows
  validation: 398 epochs / 9552 rows
  holdout: 397 epochs / 9528 rows

Subject 28/65: 095 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Subject 29/65: 096 -> subject_train
  train: 798 epochs / 19152 rows
  validation: 399 epochs / 9576 rows
  holdout: 400 epochs / 9600 rows

Subject 30/65: 069 -> subject_train
  train: 804 epochs / 19296 rows
  validation: 402 epochs / 9648 rows
  holdout: 403 epochs / 9672 rows

Subject 31/65: 056 -> subject_train
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 396 epochs / 9504 rows

Subject 32/65: 093 -> subject_train
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 396 epochs / 9504 rows

Subject 33/65: 087 -> subject_train
  train: 791 epochs / 18984 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Subject 34/65: 083 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 35/65: 080 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 36/65: 068 -> subject_train
  train: 796 epochs / 19104 rows
  validation: 398 epochs / 9552 rows
  holdout: 397 epochs / 9528 rows

Subject 37/65: 090 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 38/65: 081 -> subject_train
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 39/65: 088 -> subject_train
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 396 epochs / 9504 rows

Subject 40/65: 053 -> subject_train
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 396 epochs / 9504 rows

Subject 41/65: 086 -> subject_holdout
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 42/65: 071 -> subject_holdout
  train: 789 epochs / 18936 rows
  validation: 394 epochs / 9456 rows
  holdout: 395 epochs / 9480 rows

Subject 43/65: 047 -> subject_holdout
  train: 808 epochs / 19392 rows
  validation: 404 epochs / 9696 rows
  holdout: 405 epochs / 9720 rows

Subject 44/65: 098 -> subject_holdout
  train: 786 epochs / 18864 rows
  validation: 393 epochs / 9432 rows
  holdout: 393 epochs / 9432 rows

Subject 45/65: 092 -> subject_holdout
  train: 796 epochs / 19104 rows
  validation: 398 epochs / 9552 rows
  holdout: 397 epochs / 9528 rows

Subject 46/65: 078 -> subject_holdout
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 47/65: 032 -> subject_holdout
  train: 786 epochs / 18864 rows
  validation: 393 epochs / 9432 rows
  holdout: 392 epochs / 9408 rows

Subject 48/65: 072 -> subject_holdout
  train: 780 epochs / 18720 rows
  validation: 390 epochs / 9360 rows
  holdout: 390 epochs / 9360 rows

Subject 49/65: 060 -> subject_holdout
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 397 epochs / 9528 rows

Subject 50/65: 089 -> subject_holdout
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 397 epochs / 9528 rows

Subject 51/65: 033 -> subject_holdout
  train: 775 epochs / 18600 rows
  validation: 388 epochs / 9312 rows
  holdout: 387 epochs / 9288 rows

Subject 52/65: 094 -> subject_holdout
  train: 710 epochs / 17040 rows
  validation: 355 epochs / 8520 rows
  holdout: 355 epochs / 8520 rows

Subject 53/65: 039 -> subject_holdout
  train: 788 epochs / 18912 rows
  validation: 394 epochs / 9456 rows
  holdout: 394 epochs / 9456 rows

Subject 54/65: 046 -> subject_holdout
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 396 epochs / 9504 rows

Subject 55/65: 084 -> subject_holdout
  train: 791 epochs / 18984 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Subject 56/65: 057 -> subject_holdout
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 395 epochs / 9480 rows

Subject 57/65: 075 -> subject_holdout
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 397 epochs / 9528 rows

Subject 58/65: 063 -> subject_holdout
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Subject 59/65: 061 -> subject_holdout
  train: 793 epochs / 19032 rows
  validation: 396 epochs / 9504 rows
  holdout: 397 epochs / 9528 rows

Subject 60/65: 082 -> subject_holdout
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Subject 61/65: 064 -> subject_holdout
  train: 791 epochs / 18984 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

Subject 62/65: 040 -> subject_holdout
  train: 783 epochs / 18792 rows
  validation: 392 epochs / 9408 rows
  holdout: 391 epochs / 9384 rows

Subject 63/65: 049 -> subject_holdout
  train: 790 epochs / 18960 rows
  validation: 395 epochs / 9480 rows
  holdout: 394 epochs / 9456 rows

Subject 64/65: 041 -> subject_holdout
  train: 794 epochs / 19056 rows
  validation: 397 epochs / 9528 rows
  holdout: 398 epochs / 9552 rows

Subject 65/65: 050 -> subject_holdout
  train: 792 epochs / 19008 rows
  validation: 396 epochs / 9504 rows
  holdout: 395 epochs / 9480 rows

========================================================================
3B EXACT 40/25 SPLIT COMPLETE
========================================================================
Development subjects: 40
Holdout subjects: 25
Verification passed: no subject overlap; epochs were split only as whole epoch_uid blocks.

Verifying output CSV schemas, subjects, and epoch sizes...

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split/subject_train/train.csv'

In [ ]:
results = build_exact_subject_split(
    directory_name=directory_name,
    output_directory=output_directory,
    development_subject_count=DEVELOPMENT_SUBJECTS,
    holdout_subject_count=HOLDOUT_SUBJECTS,
    development_train_fraction=DEVELOPMENT_TRAIN_FRACTION,
    development_validation_fraction=DEVELOPMENT_VALIDATION_FRACTION,
    holdout_train_fraction=HOLDOUT_TRAIN_FRACTION,
    holdout_validation_fraction=HOLDOUT_VALIDATION_FRACTION,
    random_state=RANDOM_STATE,
    overwrite=False,
)

Discovering subjects...
Indexing file 1/130: sub-032_task-memory_eeg_processed.csv
Indexing file 2/130: sub-032_task-rest_eeg_processed.csv
Indexing file 3/130: sub-033_task-memory_eeg_processed.csv
Indexing file 4/130: sub-033_task-rest_eeg_processed.csv

KeyboardInterrupt:

In [ ]:
from pathlib import Path

root = Path(
    "/content/drive/MyDrive/EEG Shared/Processed_data/"
    "Kosachenko_All_Subjects"
)

print("Looking for train.csv files:\n")

for p in root.rglob("train.csv"):
    print(p)

print("\nLooking for validation.csv files:\n")

for p in root.rglob("validation.csv"):
    print(p)

print("\nLooking for holdout.csv files:\n")

for p in root.rglob("holdout.csv"):
    print(p)

Looking for train.csv files:

/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Splits/train.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split/subject_holdout/train.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Hierarchical_Splits/subject_train/train.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Hierarchical_Splits/subject_holdout/train.csv

Looking for validation.csv files:

/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split/subject_train/validation.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split/subject_holdout/validation.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Hierarchical_Splits/subject_train/validation.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Hierarchical_Splits/subject_holdout/validation.csv

Looking for holdout.csv files:

/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Splits/holdout.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split/subject_train/holdout.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split/subject_holdout/holdout.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Hierarchical_Splits/subject_train/holdout.csv
/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Hierarchical_Splits/subject_holdout/holdout.csv

In [ ]:
from pathlib import Path
import pandas as pd

# ============================================================
# 3B REPAIR — recreate ONLY subject_train/train.csv
# ============================================================

SOURCE_DIR = Path(
    "/content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects"
)

OUTPUT_DIR = SOURCE_DIR / "3B_Exact_40_25_Split"
MANIFEST_PATH = OUTPUT_DIR / "subject_assignments.csv"
TARGET_PATH = OUTPUT_DIR / "subject_train" / "train.csv"

RANDOM_STATE = 1
TRAIN_FRACTION = 0.50
VALIDATION_FRACTION = 0.25


# ------------------------------------------------------------
# Normalize subject IDs
# Makes 051, 51, 51.0 all become "51"
# ------------------------------------------------------------

def normalize_subject_id(value):
    value = str(value).strip().replace(".0", "")

    if value.isdigit():
        return str(int(value))

    return value


# ------------------------------------------------------------
# Safety checks
# ------------------------------------------------------------

if TARGET_PATH.exists():
    raise FileExistsError(
        f"{TARGET_PATH} already exists.\n"
        "Repair stopped so nothing gets duplicated."
    )

if not MANIFEST_PATH.exists():
    raise FileNotFoundError(
        f"Missing subject assignment manifest:\n{MANIFEST_PATH}"
    )


# ------------------------------------------------------------
# Load exact original subject assignments
# ------------------------------------------------------------

manifest = pd.read_csv(MANIFEST_PATH)

development_subjects = [
    normalize_subject_id(x)
    for x in manifest.loc[
        manifest["subject_split"] == "subject_train",
        "subject_id"
    ].tolist()
]

print("Development subjects found:", len(development_subjects))

if len(development_subjects) != 40:
    raise RuntimeError(
        f"Expected 40 development subjects, "
        f"found {len(development_subjects)}"
    )


# ------------------------------------------------------------
# Find original processed CSVs
# ------------------------------------------------------------

all_processed = sorted(SOURCE_DIR.rglob("*_processed.csv"))

# Ignore any 3B output directories
source_files = [
    p for p in all_processed
    if not any(part.startswith("3B_") for part in p.parts)
]

print("Source processed files found:", len(source_files))

if len(source_files) == 0:
    raise RuntimeError("No original processed CSV files were found.")


# ------------------------------------------------------------
# Match source files to subjects
# ------------------------------------------------------------

subject_to_files = {}

for file_path in source_files:

    try:
        parsed_subject = _subject_from_filename(file_path)
    except Exception:
        continue

    parsed_subject = normalize_subject_id(parsed_subject)

    subject_to_files.setdefault(
        parsed_subject, []
    ).append(file_path)


print("Subjects found in source files:", len(subject_to_files))


# ------------------------------------------------------------
# Get same schema used by original 3B
# ------------------------------------------------------------

first_source = source_files[0]

first_frame = _read_csv_with_retries(first_source)

master_source_columns = list(first_frame.columns)
master_columns = list(master_source_columns)

for column in ["subject_split", "sample_split"]:
    if column not in master_columns:
        master_columns.append(column)

del first_frame


# ------------------------------------------------------------
# Create target directory
# ------------------------------------------------------------

TARGET_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# Rebuild TRAIN ONLY for the 40 development subjects
# ------------------------------------------------------------

total_epochs = 0
total_rows = 0

for number, subject_id in enumerate(
    development_subjects,
    start=1
):

    subject_id = normalize_subject_id(subject_id)

    if subject_id not in subject_to_files:
        raise RuntimeError(
            f"No original processed files found "
            f"for subject {subject_id}"
        )

    print(
        f"\nRepairing subject "
        f"{number}/40: {subject_id}"
    )

    frames = []

    for file_path in subject_to_files[subject_id]:

        frame = _read_csv_with_retries(
            file_path
        )

        frame = _normalize_source_frame(
            frame,
            file_path,
            master_source_columns,
        )

        frames.append(frame)

    if not frames:
        raise RuntimeError(
            f"No readable files for subject {subject_id}"
        )

    subject_data = pd.concat(
        frames,
        ignore_index=True
    )

    del frames


    # --------------------------------------------------------
    # Keep only complete 24-row epochs
    # --------------------------------------------------------

    counts = (
        subject_data
        .groupby("epoch_uid")
        .size()
    )

    valid_epoch_ids = (
        counts[counts == 24]
        .index
        .tolist()
    )

    incomplete = int(
        (counts != 24).sum()
    )

    if incomplete:
        print(
            f"  Dropping {incomplete} "
            f"incomplete epochs"
        )

    subject_data = subject_data[
        subject_data["epoch_uid"].isin(
            valid_epoch_ids
        )
    ].copy()


    # --------------------------------------------------------
    # SAME 50 / 25 / 25 split as original 3B
    # --------------------------------------------------------

    fractions = {
        "train": TRAIN_FRACTION,
        "validation": VALIDATION_FRACTION,
        "holdout":
            1.0
            - TRAIN_FRACTION
            - VALIDATION_FRACTION,
    }

    # IMPORTANT:
    # Use the zero-padded subject ID for the seed.
    #
    # Original 3B used IDs such as "051", not "51",
    # when calculating the deterministic seed.
    original_seed_subject = str(subject_id).zfill(3)

    split_ids = _split_epoch_ids(
        valid_epoch_ids,
        fractions,
        RANDOM_STATE
        + sum(
            ord(c)
            for c in original_seed_subject
        ),
    )

    train_ids = split_ids["train"]


    # --------------------------------------------------------
    # Select training epochs
    # --------------------------------------------------------

    train_frame = subject_data[
        subject_data["epoch_uid"].isin(
            train_ids
        )
    ].copy()

    train_frame["subject_split"] = (
        "subject_train"
    )

    train_frame["sample_split"] = "train"


    # --------------------------------------------------------
    # Append ONLY to missing train.csv
    # --------------------------------------------------------

    _append_frame(
        train_frame,
        TARGET_PATH,
        master_columns,
    )

    total_epochs += len(train_ids)
    total_rows += len(train_frame)

    print(
        f"  restored train: "
        f"{len(train_ids)} epochs / "
        f"{len(train_frame)} rows"
    )

    del subject_data
    del train_frame


# ============================================================
# Verification
# ============================================================

print("\n" + "=" * 70)
print("REPAIR COMPLETE")
print("=" * 70)

print("Created:", TARGET_PATH)
print("Subjects expected:", 40)
print("Training epochs:", total_epochs)
print("Rows:", total_rows)


dtype_map = {
    column: "string"
    for column in [
        "subject_id",
        "subject",
        "epoch_uid",
    ]
    if column in master_columns
}

check = pd.read_csv(
    TARGET_PATH,
    low_memory=False,
    dtype=dtype_map if dtype_map else None,
)


# Check columns
if list(check.columns) != master_columns:
    raise RuntimeError(
        "Column schema does not match "
        "the original 3B schema."
    )


# Determine subject column
subject_col = (
    "subject_id"
    if "subject_id" in check.columns
    else "subject"
)


actual_subjects = {
    normalize_subject_id(x)
    for x in (
        check[subject_col]
        .dropna()
        .tolist()
    )
}

expected_subjects = set(
    development_subjects
)


missing_subjects = (
    expected_subjects
    - actual_subjects
)

unexpected_subjects = (
    actual_subjects
    - expected_subjects
)


print("\nVerification:")
print(
    "Subjects in repaired file:",
    len(actual_subjects)
)

print(
    "Expected subjects:",
    len(expected_subjects)
)


if missing_subjects:
    raise RuntimeError(
        f"Missing subjects: "
        f"{sorted(missing_subjects)}"
    )

if unexpected_subjects:
    raise RuntimeError(
        f"Unexpected subjects: "
        f"{sorted(unexpected_subjects)}"
    )


# Check epoch sizes
epoch_sizes = (
    check
    .groupby("epoch_uid")
    .size()
)

bad_epochs = (
    epoch_sizes[
        epoch_sizes != 24
    ]
)

print(
    "Epochs:",
    len(epoch_sizes)
)

print(
    "Bad epoch sizes:",
    len(bad_epochs)
)


if len(bad_epochs) != 0:
    raise RuntimeError(
        f"{len(bad_epochs)} epochs "
        f"do not contain exactly 24 rows."
    )


# Check split labels
if set(check["subject_split"].dropna().unique()) != {
    "subject_train"
}:
    raise RuntimeError(
        "Incorrect subject_split labels."
    )

if set(check["sample_split"].dropna().unique()) != {
    "train"
}:
    raise RuntimeError(
        "Incorrect sample_split labels."
    )


print("\n" + "=" * 70)
print(
    "PASS — subject_train/train.csv "
    "successfully restored."
)
print("=" * 70)

Development subjects found: 40
Source processed files found: 130
Subjects found in source files: 65

Repairing subject 1/40: 51
  restored train: 794 epochs / 19056 rows

Repairing subject 2/40: 79
  restored train: 794 epochs / 19056 rows

Repairing subject 3/40: 45
  restored train: 789 epochs / 18936 rows

Repairing subject 4/40: 35
  restored train: 794 epochs / 19056 rows

Repairing subject 5/40: 91
  restored train: 796 epochs / 19104 rows

Repairing subject 6/40: 74
  restored train: 789 epochs / 18936 rows

Repairing subject 7/40: 52
  restored train: 788 epochs / 18912 rows

Repairing subject 8/40: 38
  restored train: 784 epochs / 18816 rows

Repairing subject 9/40: 54
  restored train: 802 epochs / 19248 rows

Repairing subject 10/40: 36
  restored train: 788 epochs / 18912 rows

Repairing subject 11/40: 34
  restored train: 782 epochs / 18768 rows

Repairing subject 12/40: 70
  restored train: 790 epochs / 18960 rows

Repairing subject 13/40: 43
  restored train: 790 epochs / 18960 rows

Repairing subject 14/40: 97
  restored train: 792 epochs / 19008 rows

Repairing subject 15/40: 59
  restored train: 792 epochs / 19008 rows

Repairing subject 16/40: 65
  restored train: 794 epochs / 19056 rows

Repairing subject 17/40: 62
  restored train: 790 epochs / 18960 rows

Repairing subject 18/40: 42
  restored train: 802 epochs / 19248 rows

Repairing subject 19/40: 58
  restored train: 789 epochs / 18936 rows

Repairing subject 20/40: 73
  restored train: 792 epochs / 19008 rows

Repairing subject 21/40: 55
  restored train: 789 epochs / 18936 rows

Repairing subject 22/40: 44
  restored train: 790 epochs / 18960 rows

Repairing subject 23/40: 85
  restored train: 790 epochs / 18960 rows

Repairing subject 24/40: 77
  restored train: 793 epochs / 19032 rows

Repairing subject 25/40: 48
  restored train: 800 epochs / 19200 rows

Repairing subject 26/40: 76
  restored train: 790 epochs / 18960 rows

Repairing subject 27/40: 67
  restored train: 795 epochs / 19080 rows

Repairing subject 28/40: 95
  restored train: 790 epochs / 18960 rows

Repairing subject 29/40: 96
  restored train: 798 epochs / 19152 rows

Repairing subject 30/40: 69
  restored train: 804 epochs / 19296 rows

Repairing subject 31/40: 56
  restored train: 792 epochs / 19008 rows

Repairing subject 32/40: 93
  restored train: 794 epochs / 19056 rows

Repairing subject 33/40: 87
  restored train: 791 epochs / 18984 rows

Repairing subject 34/40: 83
  restored train: 790 epochs / 18960 rows

Repairing subject 35/40: 80
  restored train: 790 epochs / 18960 rows

Repairing subject 36/40: 68
  restored train: 796 epochs / 19104 rows

Repairing subject 37/40: 90
  restored train: 790 epochs / 18960 rows

Repairing subject 38/40: 81
  restored train: 790 epochs / 18960 rows

Repairing subject 39/40: 88
  restored train: 792 epochs / 19008 rows

Repairing subject 40/40: 53
  restored train: 792 epochs / 19008 rows

======================================================================
REPAIR COMPLETE
======================================================================
Created: /content/drive/MyDrive/EEG Shared/Processed_data/Kosachenko_All_Subjects/3B_Exact_40_25_Split/subject_train/train.csv
Subjects expected: 40
Training epochs: 31687
Rows: 760488

Verification:
Subjects in repaired file: 40
Expected subjects: 40
Epochs: 31687
Bad epoch sizes: 0

======================================================================
PASS — subject_train/train.csv successfully restored.
======================================================================

In [ ]:
from pathlib import Path

p = Path(
    "/content/drive/MyDrive/EEG Shared/Processed_data/"
    "Kosachenko_All_Subjects/3B_Exact_40_25_Split/"
    "subject_train/train.csv"
)

print("Exists:", p.exists())

if p.exists():
    print("Size:", p.stat().st_size)

Exists: True
Size: 1807477159

In [ ]:
import sys
import importlib

CODE_DIR = "/content/drive/MyDrive/EEG Shared/Code/Code Luke"

if CODE_DIR not in sys.path:
    sys.path.append(CODE_DIR)

module_name = "load_data_3b_exact_40_25_split_50_25_25"

m = importlib.import_module(module_name)
m = importlib.reload(m)

_read_csv_with_retries = m._read_csv_with_retries
_subject_from_filename = m._subject_from_filename
_normalize_source_frame = m._normalize_source_frame
_split_epoch_ids = m._split_epoch_ids
_append_frame = m._append_frame

print("3B repair functions loaded successfully.")

3B repair functions loaded successfully.

In [ ]:
import sys
import importlib

CODE_DIR = "/content/drive/MyDrive/EEG Shared/Code/Code Luke"

if CODE_DIR not in sys.path:
    sys.path.append(CODE_DIR)

module_name = "load_data_3b_exact_40_25_split_50_25_25"

m = importlib.import_module(module_name)
m = importlib.reload(m)

_read_csv_with_retries = m._read_csv_with_retries
_subject_from_filename = m._subject_from_filename
_normalize_source_frame = m._normalize_source_frame
_split_epoch_ids = m._split_epoch_ids
_append_frame = m._append_frame

print("3B repair functions loaded successfully.")

ModuleNotFoundError: No module named 'load_data_3b_exact_40_25_split_50_25_25'

In [ ]:
results['manifest'].groupby('subject_split')['subject_id'].nunique()